#! /bin/bash



echo "$(date): Starting equilibration in FXR_12-FXR_74 protein at $(hostname)"

[ ! -f FXR_12-FXR_74/protein/lambda0/min01/min01.tpr ] && { gmx grompp -c FXR_12-FXR_74/protein/lambda0/min01/../FullSystem.pdb -r FXR_12-FXR_74/protein/lambda0/min01/../FullSystem.pdb -f FXR_12-FXR_74/protein/lambda0/min01/min01.mdp -p FXR_12-FXR_74/protein/lambda0/min01/../SystemFull.top -o FXR_12-FXR_74/protein/lambda0/min01/min01.tpr -n FXR_12-FXR_74/protein/lambda0/min01/../index.ndx -po FXR_12-FXR_74/protein/lambda0/min01/min01_mdout.mdp -maxwarn 3 > FXR_12-FXR_74/protein/lambda0/min01/min01_grompp.log 2>&1 || { echo "Failed to run command  at line ${LINENO}" && exit; } }
[ ! -f FXR_12-FXR_74/protein/lambda0/min01/min01.gro ] && { ( cd FXR_12-FXR_74/protein/lambda0/min01 && gmx mdrun --deffnm min01 > min01_mdrun_log.log 2>&1 ) || { echo "Failed to run command  at line ${LINENO}" && exit; } }
[ ! -f FXR_12-FXR_74/protein/lambda0/min02/min02.tpr ] && { gmx grompp -c FXR_12-FXR_74/protein/lambda0/min01/min01.gro -r FXR_12-FXR_74/protein/lambda0/min01/min01.gro -f FXR_12-FXR_74/protein/lambda0/min02/min02.mdp -p FXR_12-FXR_74/protein/lambda0/min02/../SystemFull.top -o FXR_12-FXR_74/protein/lambda0/min02/min02.tpr -n FXR_12-FXR_74/protein/lambda0/min02/../index.ndx -po FXR_12-FXR_74/protein/lambda0/min02/min02_mdout.mdp -maxwarn 3 > FXR_12-FXR_74/protein/lambda0/min02/min02_grompp.log 2>&1 || { echo "Failed to run command  at line ${LINENO}" && exit; } }
[ ! -f FXR_12-FXR_74/protein/lambda0/min02/min02.gro ] && { ( cd FXR_12-FXR_74/protein/lambda0/min02 && gmx mdrun --deffnm min02 > min02_mdrun_log.log 2>&1 ) || { echo "Failed to run command  at line ${LINENO}" && exit; } }
[ ! -f FXR_12-FXR_74/protein/lambda0/min03/min03.tpr ] && { gmx grompp -c FXR_12-FXR_74/protein/lambda0/min02/min02.gro -r FXR_12-FXR_74/protein/lambda0/min02/min02.gro -f FXR_12-FXR_74/protein/lambda0/min03/min03.mdp -p FXR_12-FXR_74/protein/lambda0/min03/../SystemFull.top -o FXR_12-FXR_74/protein/lambda0/min03/min03.tpr -n FXR_12-FXR_74/protein/lambda0/min03/../index.ndx -po FXR_12-FXR_74/protein/lambda0/min03/min03_mdout.mdp -maxwarn 3 > FXR_12-FXR_74/protein/lambda0/min03/min03_grompp.log 2>&1 || { echo "Failed to run command  at line ${LINENO}" && exit; } }
[ ! -f FXR_12-FXR_74/protein/lambda0/min03/min03.gro ] && { ( cd FXR_12-FXR_74/protein/lambda0/min03 && gmx mdrun --deffnm min03 > min03_mdrun_log.log 2>&1 ) || { echo "Failed to run command  at line ${LINENO}" && exit; } }
[ ! -f FXR_12-FXR_74/protein/lambda0/nve/nve.tpr ] && { gmx grompp -c FXR_12-FXR_74/protein/lambda0/min03/min03.gro -r FXR_12-FXR_74/protein/lambda0/min03/min03.gro -f FXR_12-FXR_74/protein/lambda0/nve/nve.mdp -p FXR_12-FXR_74/protein/lambda0/nve/../SystemFull.top -o FXR_12-FXR_74/protein/lambda0/nve/nve.tpr -n FXR_12-FXR_74/protein/lambda0/nve/../index.ndx -po FXR_12-FXR_74/protein/lambda0/nve/nve_mdout.mdp -maxwarn 3 > FXR_12-FXR_74/protein/lambda0/nve/nve_grompp.log 2>&1 || { echo "Failed to run command  at line ${LINENO}" && exit; } }
[ ! -f FXR_12-FXR_74/protein/lambda0/nve/nve.gro ] && { ( cd FXR_12-FXR_74/protein/lambda0/nve && gmx mdrun --deffnm nve > nve_mdrun_log.log 2>&1 ) || { echo "Failed to run command  at line ${LINENO}" && exit; } }
[ ! -f FXR_12-FXR_74/protein/lambda0/nvt/nvt.tpr ] && { gmx grompp -c FXR_12-FXR_74/protein/lambda0/nve/nve.gro -r FXR_12-FXR_74/protein/lambda0/nve/nve.gro -f FXR_12-FXR_74/protein/lambda0/nvt/nvt.mdp -p FXR_12-FXR_74/protein/lambda0/nvt/../SystemFull.top -o FXR_12-FXR_74/protein/lambda0/nvt/nvt.tpr -n FXR_12-FXR_74/protein/lambda0/nvt/../index.ndx -po FXR_12-FXR_74/protein/lambda0/nvt/nvt_mdout.mdp -maxwarn 3 > FXR_12-FXR_74/protein/lambda0/nvt/nvt_grompp.log 2>&1 || { echo "Failed to run command  at line ${LINENO}" && exit; } }
[ ! -f FXR_12-FXR_74/protein/lambda0/nvt/nvt.gro ] && { ( cd FXR_12-FXR_74/protein/lambda0/nvt && gmx mdrun --deffnm nvt > nvt_mdrun_log.log 2>&1 ) || { echo "Failed to run command  at line ${LINENO}" && exit; } }
[ ! -f FXR_12-FXR_74/protein/lambda0/npt/npt.tpr ] && { gmx grompp -c FXR_12-FXR_74/protein/lambda0/nvt/nvt.gro -r FXR_12-FXR_74/protein/lambda0/nvt/nvt.gro -f FXR_12-FXR_74/protein/lambda0/npt/npt.mdp -p FXR_12-FXR_74/protein/lambda0/npt/../SystemFull.top -o FXR_12-FXR_74/protein/lambda0/npt/npt.tpr -n FXR_12-FXR_74/protein/lambda0/npt/../index.ndx -po FXR_12-FXR_74/protein/lambda0/npt/npt_mdout.mdp -maxwarn 3 > FXR_12-FXR_74/protein/lambda0/npt/npt_grompp.log 2>&1 || { echo "Failed to run command  at line ${LINENO}" && exit; } }
[ ! -f FXR_12-FXR_74/protein/lambda0/npt/npt.gro ] && { ( cd FXR_12-FXR_74/protein/lambda0/npt && gmx mdrun --deffnm npt > npt_mdrun_log.log 2>&1 ) || { echo "Failed to run command  at line ${LINENO}" && exit; } }
[ ! -f FXR_12-FXR_74/protein/lambda0/md/md_nocont.tpr ] && { gmx grompp -c FXR_12-FXR_74/protein/lambda0/npt/npt.gro -r FXR_12-FXR_74/protein/lambda0/npt/npt.gro -t FXR_12-FXR_74/protein/lambda0/npt/npt.cpt -f FXR_12-FXR_74/protein/lambda0/md/md_nocont.mdp -po FXR_12-FXR_74/protein/lambda0/md/mdout_nocont.mdp -o FXR_12-FXR_74/protein/lambda0/md/md_nocont.tpr -n FXR_12-FXR_74/protein/lambda0/md/../../index.ndx -p FXR_12-FXR_74/protein/lambda0/md/../SystemFull.top -maxwarn 3 > FXR_12-FXR_74/protein/lambda0/md/mdout_nocont.log 2>&1 || { echo "Failed to run command  at line ${LINENO}" && exit; } }
[ ! -f FXR_12-FXR_74/protein/lambda0/md/md.tpr ] && { gmx grompp -c FXR_12-FXR_74/protein/lambda0/npt/npt.gro -r FXR_12-FXR_74/protein/lambda0/npt/npt.gro -t FXR_12-FXR_74/protein/lambda0/npt/npt.cpt -f FXR_12-FXR_74/protein/lambda0/md/md.mdp -p FXR_12-FXR_74/protein/lambda0/md/../SystemFull.top -o FXR_12-FXR_74/protein/lambda0/md/md.tpr -n FXR_12-FXR_74/protein/lambda0/md/../../index.ndx -po FXR_12-FXR_74/protein/lambda0/md/mdout.mdp -maxwarn 3 > FXR_12-FXR_74/protein/lambda0/md/mdout.log 2>&1 || { echo "Failed to run command  at line ${LINENO}" && exit; } }
cp FXR_12-FXR_74/protein/lambda0/md/md.tpr FXR_12-FXR_74/protein/md/lambda0/lambda.tpr
cp FXR_12-FXR_74/protein/lambda0/md/md_nocont.tpr FXR_12-FXR_74/protein/md/lambda0/lambda_nocont.tpr

[ ! -f FXR_12-FXR_74/protein/lambda1/min01/min01.tpr ] && { gmx grompp -c FXR_12-FXR_74/protein/lambda1/min01/../FullSystem.pdb -r FXR_12-FXR_74/protein/lambda1/min01/../FullSystem.pdb -f FXR_12-FXR_74/protein/lambda1/min01/min01.mdp -p FXR_12-FXR_74/protein/lambda1/min01/../SystemFull.top -o FXR_12-FXR_74/protein/lambda1/min01/min01.tpr -n FXR_12-FXR_74/protein/lambda1/min01/../index.ndx -po FXR_12-FXR_74/protein/lambda1/min01/min01_mdout.mdp -maxwarn 3 > FXR_12-FXR_74/protein/lambda1/min01/min01_grompp.log 2>&1 || { echo "Failed to run command  at line ${LINENO}" && exit; } }
[ ! -f FXR_12-FXR_74/protein/lambda1/min01/min01.gro ] && { ( cd FXR_12-FXR_74/protein/lambda1/min01 && gmx mdrun --deffnm min01 > min01_mdrun_log.log 2>&1 ) || { echo "Failed to run command  at line ${LINENO}" && exit; } }
[ ! -f FXR_12-FXR_74/protein/lambda1/min02/min02.tpr ] && { gmx grompp -c FXR_12-FXR_74/protein/lambda1/min01/min01.gro -r FXR_12-FXR_74/protein/lambda1/min01/min01.gro -f FXR_12-FXR_74/protein/lambda1/min02/min02.mdp -p FXR_12-FXR_74/protein/lambda1/min02/../SystemFull.top -o FXR_12-FXR_74/protein/lambda1/min02/min02.tpr -n FXR_12-FXR_74/protein/lambda1/min02/../index.ndx -po FXR_12-FXR_74/protein/lambda1/min02/min02_mdout.mdp -maxwarn 3 > FXR_12-FXR_74/protein/lambda1/min02/min02_grompp.log 2>&1 || { echo "Failed to run command  at line ${LINENO}" && exit; } }
[ ! -f FXR_12-FXR_74/protein/lambda1/min02/min02.gro ] && { ( cd FXR_12-FXR_74/protein/lambda1/min02 && gmx mdrun --deffnm min02 > min02_mdrun_log.log 2>&1 ) || { echo "Failed to run command  at line ${LINENO}" && exit; } }
[ ! -f FXR_12-FXR_74/protein/lambda1/min03/min03.tpr ] && { gmx grompp -c FXR_12-FXR_74/protein/lambda1/min02/min02.gro -r FXR_12-FXR_74/protein/lambda1/min02/min02.gro -f FXR_12-FXR_74/protein/lambda1/min03/min03.mdp -p FXR_12-FXR_74/protein/lambda1/min03/../SystemFull.top -o FXR_12-FXR_74/protein/lambda1/min03/min03.tpr -n FXR_12-FXR_74/protein/lambda1/min03/../index.ndx -po FXR_12-FXR_74/protein/lambda1/min03/min03_mdout.mdp -maxwarn 3 > FXR_12-FXR_74/protein/lambda1/min03/min03_grompp.log 2>&1 || { echo "Failed to run command  at line ${LINENO}" && exit; } }
[ ! -f FXR_12-FXR_74/protein/lambda1/min03/min03.gro ] && { ( cd FXR_12-FXR_74/protein/lambda1/min03 && gmx mdrun --deffnm min03 > min03_mdrun_log.log 2>&1 ) || { echo "Failed to run command  at line ${LINENO}" && exit; } }
[ ! -f FXR_12-FXR_74/protein/lambda1/nve/nve.tpr ] && { gmx grompp -c FXR_12-FXR_74/protein/lambda1/min03/min03.gro -r FXR_12-FXR_74/protein/lambda1/min03/min03.gro -f FXR_12-FXR_74/protein/lambda1/nve/nve.mdp -p FXR_12-FXR_74/protein/lambda1/nve/../SystemFull.top -o FXR_12-FXR_74/protein/lambda1/nve/nve.tpr -n FXR_12-FXR_74/protein/lambda1/nve/../index.ndx -po FXR_12-FXR_74/protein/lambda1/nve/nve_mdout.mdp -maxwarn 3 > FXR_12-FXR_74/protein/lambda1/nve/nve_grompp.log 2>&1 || { echo "Failed to run command  at line ${LINENO}" && exit; } }
[ ! -f FXR_12-FXR_74/protein/lambda1/nve/nve.gro ] && { ( cd FXR_12-FXR_74/protein/lambda1/nve && gmx mdrun --deffnm nve > nve_mdrun_log.log 2>&1 ) || { echo "Failed to run command  at line ${LINENO}" && exit; } }
[ ! -f FXR_12-FXR_74/protein/lambda1/nvt/nvt.tpr ] && { gmx grompp -c FXR_12-FXR_74/protein/lambda1/nve/nve.gro -r FXR_12-FXR_74/protein/lambda1/nve/nve.gro -f FXR_12-FXR_74/protein/lambda1/nvt/nvt.mdp -p FXR_12-FXR_74/protein/lambda1/nvt/../SystemFull.top -o FXR_12-FXR_74/protein/lambda1/nvt/nvt.tpr -n FXR_12-FXR_74/protein/lambda1/nvt/../index.ndx -po FXR_12-FXR_74/protein/lambda1/nvt/nvt_mdout.mdp -maxwarn 3 > FXR_12-FXR_74/protein/lambda1/nvt/nvt_grompp.log 2>&1 || { echo "Failed to run command  at line ${LINENO}" && exit; } }
[ ! -f FXR_12-FXR_74/protein/lambda1/nvt/nvt.gro ] && { ( cd FXR_12-FXR_74/protein/lambda1/nvt && gmx mdrun --deffnm nvt > nvt_mdrun_log.log 2>&1 ) || { echo "Failed to run command  at line ${LINENO}" && exit; } }
[ ! -f FXR_12-FXR_74/protein/lambda1/npt/npt.tpr ] && { gmx grompp -c FXR_12-FXR_74/protein/lambda1/nvt/nvt.gro -r FXR_12-FXR_74/protein/lambda1/nvt/nvt.gro -f FXR_12-FXR_74/protein/lambda1/npt/npt.mdp -p FXR_12-FXR_74/protein/lambda1/npt/../SystemFull.top -o FXR_12-FXR_74/protein/lambda1/npt/npt.tpr -n FXR_12-FXR_74/protein/lambda1/npt/../index.ndx -po FXR_12-FXR_74/protein/lambda1/npt/npt_mdout.mdp -maxwarn 3 > FXR_12-FXR_74/protein/lambda1/npt/npt_grompp.log 2>&1 || { echo "Failed to run command  at line ${LINENO}" && exit; } }
[ ! -f FXR_12-FXR_74/protein/lambda1/npt/npt.gro ] && { ( cd FXR_12-FXR_74/protein/lambda1/npt && gmx mdrun --deffnm npt > npt_mdrun_log.log 2>&1 ) || { echo "Failed to run command  at line ${LINENO}" && exit; } }
[ ! -f FXR_12-FXR_74/protein/lambda1/md/md_nocont.tpr ] && { gmx grompp -c FXR_12-FXR_74/protein/lambda1/npt/npt.gro -r FXR_12-FXR_74/protein/lambda1/npt/npt.gro -t FXR_12-FXR_74/protein/lambda1/npt/npt.cpt -f FXR_12-FXR_74/protein/lambda1/md/md_nocont.mdp -po FXR_12-FXR_74/protein/lambda1/md/mdout_nocont.mdp -o FXR_12-FXR_74/protein/lambda1/md/md_nocont.tpr -n FXR_12-FXR_74/protein/lambda1/md/../../index.ndx -p FXR_12-FXR_74/protein/lambda1/md/../SystemFull.top -maxwarn 3 > FXR_12-FXR_74/protein/lambda1/md/mdout_nocont.log 2>&1 || { echo "Failed to run command  at line ${LINENO}" && exit; } }
[ ! -f FXR_12-FXR_74/protein/lambda1/md/md.tpr ] && { gmx grompp -c FXR_12-FXR_74/protein/lambda1/npt/npt.gro -r FXR_12-FXR_74/protein/lambda1/npt/npt.gro -t FXR_12-FXR_74/protein/lambda1/npt/npt.cpt -f FXR_12-FXR_74/protein/lambda1/md/md.mdp -p FXR_12-FXR_74/protein/lambda1/md/../SystemFull.top -o FXR_12-FXR_74/protein/lambda1/md/md.tpr -n FXR_12-FXR_74/protein/lambda1/md/../../index.ndx -po FXR_12-FXR_74/protein/lambda1/md/mdout.mdp -maxwarn 3 > FXR_12-FXR_74/protein/lambda1/md/mdout.log 2>&1 || { echo "Failed to run command  at line ${LINENO}" && exit; } }
cp FXR_12-FXR_74/protein/lambda1/md/md.tpr FXR_12-FXR_74/protein/md/lambda1/lambda.tpr
cp FXR_12-FXR_74/protein/lambda1/md/md_nocont.tpr FXR_12-FXR_74/protein/md/lambda1/lambda_nocont.tpr

[ ! -f FXR_12-FXR_74/protein/lambda2/min01/min01.tpr ] && { gmx grompp -c FXR_12-FXR_74/protein/lambda2/min01/../FullSystem.pdb -r FXR_12-FXR_74/protein/lambda2/min01/../FullSystem.pdb -f FXR_12-FXR_74/protein/lambda2/min01/min01.mdp -p FXR_12-FXR_74/protein/lambda2/min01/../SystemFull.top -o FXR_12-FXR_74/protein/lambda2/min01/min01.tpr -n FXR_12-FXR_74/protein/lambda2/min01/../index.ndx -po FXR_12-FXR_74/protein/lambda2/min01/min01_mdout.mdp -maxwarn 3 > FXR_12-FXR_74/protein/lambda2/min01/min01_grompp.log 2>&1 || { echo "Failed to run command  at line ${LINENO}" && exit; } }
[ ! -f FXR_12-FXR_74/protein/lambda2/min01/min01.gro ] && { ( cd FXR_12-FXR_74/protein/lambda2/min01 && gmx mdrun --deffnm min01 > min01_mdrun_log.log 2>&1 ) || { echo "Failed to run command  at line ${LINENO}" && exit; } }
[ ! -f FXR_12-FXR_74/protein/lambda2/min02/min02.tpr ] && { gmx grompp -c FXR_12-FXR_74/protein/lambda2/min01/min01.gro -r FXR_12-FXR_74/protein/lambda2/min01/min01.gro -f FXR_12-FXR_74/protein/lambda2/min02/min02.mdp -p FXR_12-FXR_74/protein/lambda2/min02/../SystemFull.top -o FXR_12-FXR_74/protein/lambda2/min02/min02.tpr -n FXR_12-FXR_74/protein/lambda2/min02/../index.ndx -po FXR_12-FXR_74/protein/lambda2/min02/min02_mdout.mdp -maxwarn 3 > FXR_12-FXR_74/protein/lambda2/min02/min02_grompp.log 2>&1 || { echo "Failed to run command  at line ${LINENO}" && exit; } }
[ ! -f FXR_12-FXR_74/protein/lambda2/min02/min02.gro ] && { ( cd FXR_12-FXR_74/protein/lambda2/min02 && gmx mdrun --deffnm min02 > min02_mdrun_log.log 2>&1 ) || { echo "Failed to run command  at line ${LINENO}" && exit; } }
[ ! -f FXR_12-FXR_74/protein/lambda2/min03/min03.tpr ] && { gmx grompp -c FXR_12-FXR_74/protein/lambda2/min02/min02.gro -r FXR_12-FXR_74/protein/lambda2/min02/min02.gro -f FXR_12-FXR_74/protein/lambda2/min03/min03.mdp -p FXR_12-FXR_74/protein/lambda2/min03/../SystemFull.top -o FXR_12-FXR_74/protein/lambda2/min03/min03.tpr -n FXR_12-FXR_74/protein/lambda2/min03/../index.ndx -po FXR_12-FXR_74/protein/lambda2/min03/min03_mdout.mdp -maxwarn 3 > FXR_12-FXR_74/protein/lambda2/min03/min03_grompp.log 2>&1 || { echo "Failed to run command  at line ${LINENO}" && exit; } }
[ ! -f FXR_12-FXR_74/protein/lambda2/min03/min03.gro ] && { ( cd FXR_12-FXR_74/protein/lambda2/min03 && gmx mdrun --deffnm min03 > min03_mdrun_log.log 2>&1 ) || { echo "Failed to run command  at line ${LINENO}" && exit; } }
[ ! -f FXR_12-FXR_74/protein/lambda2/nve/nve.tpr ] && { gmx grompp -c FXR_12-FXR_74/protein/lambda2/min03/min03.gro -r FXR_12-FXR_74/protein/lambda2/min03/min03.gro -f FXR_12-FXR_74/protein/lambda2/nve/nve.mdp -p FXR_12-FXR_74/protein/lambda2/nve/../SystemFull.top -o FXR_12-FXR_74/protein/lambda2/nve/nve.tpr -n FXR_12-FXR_74/protein/lambda2/nve/../index.ndx -po FXR_12-FXR_74/protein/lambda2/nve/nve_mdout.mdp -maxwarn 3 > FXR_12-FXR_74/protein/lambda2/nve/nve_grompp.log 2>&1 || { echo "Failed to run command  at line ${LINENO}" && exit; } }
[ ! -f FXR_12-FXR_74/protein/lambda2/nve/nve.gro ] && { ( cd FXR_12-FXR_74/protein/lambda2/nve && gmx mdrun --deffnm nve > nve_mdrun_log.log 2>&1 ) || { echo "Failed to run command  at line ${LINENO}" && exit; } }
[ ! -f FXR_12-FXR_74/protein/lambda2/nvt/nvt.tpr ] && { gmx grompp -c FXR_12-FXR_74/protein/lambda2/nve/nve.gro -r FXR_12-FXR_74/protein/lambda2/nve/nve.gro -f FXR_12-FXR_74/protein/lambda2/nvt/nvt.mdp -p FXR_12-FXR_74/protein/lambda2/nvt/../SystemFull.top -o FXR_12-FXR_74/protein/lambda2/nvt/nvt.tpr -n FXR_12-FXR_74/protein/lambda2/nvt/../index.ndx -po FXR_12-FXR_74/protein/lambda2/nvt/nvt_mdout.mdp -maxwarn 3 > FXR_12-FXR_74/protein/lambda2/nvt/nvt_grompp.log 2>&1 || { echo "Failed to run command  at line ${LINENO}" && exit; } }
[ ! -f FXR_12-FXR_74/protein/lambda2/nvt/nvt.gro ] && { ( cd FXR_12-FXR_74/protein/lambda2/nvt && gmx mdrun --deffnm nvt > nvt_mdrun_log.log 2>&1 ) || { echo "Failed to run command  at line ${LINENO}" && exit; } }
[ ! -f FXR_12-FXR_74/protein/lambda2/npt/npt.tpr ] && { gmx grompp -c FXR_12-FXR_74/protein/lambda2/nvt/nvt.gro -r FXR_12-FXR_74/protein/lambda2/nvt/nvt.gro -f FXR_12-FXR_74/protein/lambda2/npt/npt.mdp -p FXR_12-FXR_74/protein/lambda2/npt/../SystemFull.top -o FXR_12-FXR_74/protein/lambda2/npt/npt.tpr -n FXR_12-FXR_74/protein/lambda2/npt/../index.ndx -po FXR_12-FXR_74/protein/lambda2/npt/npt_mdout.mdp -maxwarn 3 > FXR_12-FXR_74/protein/lambda2/npt/npt_grompp.log 2>&1 || { echo "Failed to run command  at line ${LINENO}" && exit; } }
[ ! -f FXR_12-FXR_74/protein/lambda2/npt/npt.gro ] && { ( cd FXR_12-FXR_74/protein/lambda2/npt && gmx mdrun --deffnm npt > npt_mdrun_log.log 2>&1 ) || { echo "Failed to run command  at line ${LINENO}" && exit; } }
[ ! -f FXR_12-FXR_74/protein/lambda2/md/md_nocont.tpr ] && { gmx grompp -c FXR_12-FXR_74/protein/lambda2/npt/npt.gro -r FXR_12-FXR_74/protein/lambda2/npt/npt.gro -t FXR_12-FXR_74/protein/lambda2/npt/npt.cpt -f FXR_12-FXR_74/protein/lambda2/md/md_nocont.mdp -po FXR_12-FXR_74/protein/lambda2/md/mdout_nocont.mdp -o FXR_12-FXR_74/protein/lambda2/md/md_nocont.tpr -n FXR_12-FXR_74/protein/lambda2/md/../../index.ndx -p FXR_12-FXR_74/protein/lambda2/md/../SystemFull.top -maxwarn 3 > FXR_12-FXR_74/protein/lambda2/md/mdout_nocont.log 2>&1 || { echo "Failed to run command  at line ${LINENO}" && exit; } }
[ ! -f FXR_12-FXR_74/protein/lambda2/md/md.tpr ] && { gmx grompp -c FXR_12-FXR_74/protein/lambda2/npt/npt.gro -r FXR_12-FXR_74/protein/lambda2/npt/npt.gro -t FXR_12-FXR_74/protein/lambda2/npt/npt.cpt -f FXR_12-FXR_74/protein/lambda2/md/md.mdp -p FXR_12-FXR_74/protein/lambda2/md/../SystemFull.top -o FXR_12-FXR_74/protein/lambda2/md/md.tpr -n FXR_12-FXR_74/protein/lambda2/md/../../index.ndx -po FXR_12-FXR_74/protein/lambda2/md/mdout.mdp -maxwarn 3 > FXR_12-FXR_74/protein/lambda2/md/mdout.log 2>&1 || { echo "Failed to run command  at line ${LINENO}" && exit; } }
cp FXR_12-FXR_74/protein/lambda2/md/md.tpr FXR_12-FXR_74/protein/md/lambda2/lambda.tpr
cp FXR_12-FXR_74/protein/lambda2/md/md_nocont.tpr FXR_12-FXR_74/protein/md/lambda2/lambda_nocont.tpr

[ ! -f FXR_12-FXR_74/protein/lambda3/min01/min01.tpr ] && { gmx grompp -c FXR_12-FXR_74/protein/lambda3/min01/../FullSystem.pdb -r FXR_12-FXR_74/protein/lambda3/min01/../FullSystem.pdb -f FXR_12-FXR_74/protein/lambda3/min01/min01.mdp -p FXR_12-FXR_74/protein/lambda3/min01/../SystemFull.top -o FXR_12-FXR_74/protein/lambda3/min01/min01.tpr -n FXR_12-FXR_74/protein/lambda3/min01/../index.ndx -po FXR_12-FXR_74/protein/lambda3/min01/min01_mdout.mdp -maxwarn 3 > FXR_12-FXR_74/protein/lambda3/min01/min01_grompp.log 2>&1 || { echo "Failed to run command  at line ${LINENO}" && exit; } }
[ ! -f FXR_12-FXR_74/protein/lambda3/min01/min01.gro ] && { ( cd FXR_12-FXR_74/protein/lambda3/min01 && gmx mdrun --deffnm min01 > min01_mdrun_log.log 2>&1 ) || { echo "Failed to run command  at line ${LINENO}" && exit; } }
[ ! -f FXR_12-FXR_74/protein/lambda3/min02/min02.tpr ] && { gmx grompp -c FXR_12-FXR_74/protein/lambda3/min01/min01.gro -r FXR_12-FXR_74/protein/lambda3/min01/min01.gro -f FXR_12-FXR_74/protein/lambda3/min02/min02.mdp -p FXR_12-FXR_74/protein/lambda3/min02/../SystemFull.top -o FXR_12-FXR_74/protein/lambda3/min02/min02.tpr -n FXR_12-FXR_74/protein/lambda3/min02/../index.ndx -po FXR_12-FXR_74/protein/lambda3/min02/min02_mdout.mdp -maxwarn 3 > FXR_12-FXR_74/protein/lambda3/min02/min02_grompp.log 2>&1 || { echo "Failed to run command  at line ${LINENO}" && exit; } }
[ ! -f FXR_12-FXR_74/protein/lambda3/min02/min02.gro ] && { ( cd FXR_12-FXR_74/protein/lambda3/min02 && gmx mdrun --deffnm min02 > min02_mdrun_log.log 2>&1 ) || { echo "Failed to run command  at line ${LINENO}" && exit; } }
[ ! -f FXR_12-FXR_74/protein/lambda3/min03/min03.tpr ] && { gmx grompp -c FXR_12-FXR_74/protein/lambda3/min02/min02.gro -r FXR_12-FXR_74/protein/lambda3/min02/min02.gro -f FXR_12-FXR_74/protein/lambda3/min03/min03.mdp -p FXR_12-FXR_74/protein/lambda3/min03/../SystemFull.top -o FXR_12-FXR_74/protein/lambda3/min03/min03.tpr -n FXR_12-FXR_74/protein/lambda3/min03/../index.ndx -po FXR_12-FXR_74/protein/lambda3/min03/min03_mdout.mdp -maxwarn 3 > FXR_12-FXR_74/protein/lambda3/min03/min03_grompp.log 2>&1 || { echo "Failed to run command  at line ${LINENO}" && exit; } }
[ ! -f FXR_12-FXR_74/protein/lambda3/min03/min03.gro ] && { ( cd FXR_12-FXR_74/protein/lambda3/min03 && gmx mdrun --deffnm min03 > min03_mdrun_log.log 2>&1 ) || { echo "Failed to run command  at line ${LINENO}" && exit; } }
[ ! -f FXR_12-FXR_74/protein/lambda3/nve/nve.tpr ] && { gmx grompp -c FXR_12-FXR_74/protein/lambda3/min03/min03.gro -r FXR_12-FXR_74/protein/lambda3/min03/min03.gro -f FXR_12-FXR_74/protein/lambda3/nve/nve.mdp -p FXR_12-FXR_74/protein/lambda3/nve/../SystemFull.top -o FXR_12-FXR_74/protein/lambda3/nve/nve.tpr -n FXR_12-FXR_74/protein/lambda3/nve/../index.ndx -po FXR_12-FXR_74/protein/lambda3/nve/nve_mdout.mdp -maxwarn 3 > FXR_12-FXR_74/protein/lambda3/nve/nve_grompp.log 2>&1 || { echo "Failed to run command  at line ${LINENO}" && exit; } }
[ ! -f FXR_12-FXR_74/protein/lambda3/nve/nve.gro ] && { ( cd FXR_12-FXR_74/protein/lambda3/nve && gmx mdrun --deffnm nve > nve_mdrun_log.log 2>&1 ) || { echo "Failed to run command  at line ${LINENO}" && exit; } }
[ ! -f FXR_12-FXR_74/protein/lambda3/nvt/nvt.tpr ] && { gmx grompp -c FXR_12-FXR_74/protein/lambda3/nve/nve.gro -r FXR_12-FXR_74/protein/lambda3/nve/nve.gro -f FXR_12-FXR_74/protein/lambda3/nvt/nvt.mdp -p FXR_12-FXR_74/protein/lambda3/nvt/../SystemFull.top -o FXR_12-FXR_74/protein/lambda3/nvt/nvt.tpr -n FXR_12-FXR_74/protein/lambda3/nvt/../index.ndx -po FXR_12-FXR_74/protein/lambda3/nvt/nvt_mdout.mdp -maxwarn 3 > FXR_12-FXR_74/protein/lambda3/nvt/nvt_grompp.log 2>&1 || { echo "Failed to run command  at line ${LINENO}" && exit; } }
[ ! -f FXR_12-FXR_74/protein/lambda3/nvt/nvt.gro ] && { ( cd FXR_12-FXR_74/protein/lambda3/nvt && gmx mdrun --deffnm nvt > nvt_mdrun_log.log 2>&1 ) || { echo "Failed to run command  at line ${LINENO}" && exit; } }
[ ! -f FXR_12-FXR_74/protein/lambda3/npt/npt.tpr ] && { gmx grompp -c FXR_12-FXR_74/protein/lambda3/nvt/nvt.gro -r FXR_12-FXR_74/protein/lambda3/nvt/nvt.gro -f FXR_12-FXR_74/protein/lambda3/npt/npt.mdp -p FXR_12-FXR_74/protein/lambda3/npt/../SystemFull.top -o FXR_12-FXR_74/protein/lambda3/npt/npt.tpr -n FXR_12-FXR_74/protein/lambda3/npt/../index.ndx -po FXR_12-FXR_74/protein/lambda3/npt/npt_mdout.mdp -maxwarn 3 > FXR_12-FXR_74/protein/lambda3/npt/npt_grompp.log 2>&1 || { echo "Failed to run command  at line ${LINENO}" && exit; } }
[ ! -f FXR_12-FXR_74/protein/lambda3/npt/npt.gro ] && { ( cd FXR_12-FXR_74/protein/lambda3/npt && gmx mdrun --deffnm npt > npt_mdrun_log.log 2>&1 ) || { echo "Failed to run command  at line ${LINENO}" && exit; } }
[ ! -f FXR_12-FXR_74/protein/lambda3/md/md_nocont.tpr ] && { gmx grompp -c FXR_12-FXR_74/protein/lambda3/npt/npt.gro -r FXR_12-FXR_74/protein/lambda3/npt/npt.gro -t FXR_12-FXR_74/protein/lambda3/npt/npt.cpt -f FXR_12-FXR_74/protein/lambda3/md/md_nocont.mdp -po FXR_12-FXR_74/protein/lambda3/md/mdout_nocont.mdp -o FXR_12-FXR_74/protein/lambda3/md/md_nocont.tpr -n FXR_12-FXR_74/protein/lambda3/md/../../index.ndx -p FXR_12-FXR_74/protein/lambda3/md/../SystemFull.top -maxwarn 3 > FXR_12-FXR_74/protein/lambda3/md/mdout_nocont.log 2>&1 || { echo "Failed to run command  at line ${LINENO}" && exit; } }
[ ! -f FXR_12-FXR_74/protein/lambda3/md/md.tpr ] && { gmx grompp -c FXR_12-FXR_74/protein/lambda3/npt/npt.gro -r FXR_12-FXR_74/protein/lambda3/npt/npt.gro -t FXR_12-FXR_74/protein/lambda3/npt/npt.cpt -f FXR_12-FXR_74/protein/lambda3/md/md.mdp -p FXR_12-FXR_74/protein/lambda3/md/../SystemFull.top -o FXR_12-FXR_74/protein/lambda3/md/md.tpr -n FXR_12-FXR_74/protein/lambda3/md/../../index.ndx -po FXR_12-FXR_74/protein/lambda3/md/mdout.mdp -maxwarn 3 > FXR_12-FXR_74/protein/lambda3/md/mdout.log 2>&1 || { echo "Failed to run command  at line ${LINENO}" && exit; } }
cp FXR_12-FXR_74/protein/lambda3/md/md.tpr FXR_12-FXR_74/protein/md/lambda3/lambda.tpr
cp FXR_12-FXR_74/protein/lambda3/md/md_nocont.tpr FXR_12-FXR_74/protein/md/lambda3/lambda_nocont.tpr

[ ! -f FXR_12-FXR_74/protein/lambda4/min01/min01.tpr ] && { gmx grompp -c FXR_12-FXR_74/protein/lambda4/min01/../FullSystem.pdb -r FXR_12-FXR_74/protein/lambda4/min01/../FullSystem.pdb -f FXR_12-FXR_74/protein/lambda4/min01/min01.mdp -p FXR_12-FXR_74/protein/lambda4/min01/../SystemFull.top -o FXR_12-FXR_74/protein/lambda4/min01/min01.tpr -n FXR_12-FXR_74/protein/lambda4/min01/../index.ndx -po FXR_12-FXR_74/protein/lambda4/min01/min01_mdout.mdp -maxwarn 3 > FXR_12-FXR_74/protein/lambda4/min01/min01_grompp.log 2>&1 || { echo "Failed to run command  at line ${LINENO}" && exit; } }
[ ! -f FXR_12-FXR_74/protein/lambda4/min01/min01.gro ] && { ( cd FXR_12-FXR_74/protein/lambda4/min01 && gmx mdrun --deffnm min01 > min01_mdrun_log.log 2>&1 ) || { echo "Failed to run command  at line ${LINENO}" && exit; } }
[ ! -f FXR_12-FXR_74/protein/lambda4/min02/min02.tpr ] && { gmx grompp -c FXR_12-FXR_74/protein/lambda4/min01/min01.gro -r FXR_12-FXR_74/protein/lambda4/min01/min01.gro -f FXR_12-FXR_74/protein/lambda4/min02/min02.mdp -p FXR_12-FXR_74/protein/lambda4/min02/../SystemFull.top -o FXR_12-FXR_74/protein/lambda4/min02/min02.tpr -n FXR_12-FXR_74/protein/lambda4/min02/../index.ndx -po FXR_12-FXR_74/protein/lambda4/min02/min02_mdout.mdp -maxwarn 3 > FXR_12-FXR_74/protein/lambda4/min02/min02_grompp.log 2>&1 || { echo "Failed to run command  at line ${LINENO}" && exit; } }
[ ! -f FXR_12-FXR_74/protein/lambda4/min02/min02.gro ] && { ( cd FXR_12-FXR_74/protein/lambda4/min02 && gmx mdrun --deffnm min02 > min02_mdrun_log.log 2>&1 ) || { echo "Failed to run command  at line ${LINENO}" && exit; } }
[ ! -f FXR_12-FXR_74/protein/lambda4/min03/min03.tpr ] && { gmx grompp -c FXR_12-FXR_74/protein/lambda4/min02/min02.gro -r FXR_12-FXR_74/protein/lambda4/min02/min02.gro -f FXR_12-FXR_74/protein/lambda4/min03/min03.mdp -p FXR_12-FXR_74/protein/lambda4/min03/../SystemFull.top -o FXR_12-FXR_74/protein/lambda4/min03/min03.tpr -n FXR_12-FXR_74/protein/lambda4/min03/../index.ndx -po FXR_12-FXR_74/protein/lambda4/min03/min03_mdout.mdp -maxwarn 3 > FXR_12-FXR_74/protein/lambda4/min03/min03_grompp.log 2>&1 || { echo "Failed to run command  at line ${LINENO}" && exit; } }
[ ! -f FXR_12-FXR_74/protein/lambda4/min03/min03.gro ] && { ( cd FXR_12-FXR_74/protein/lambda4/min03 && gmx mdrun --deffnm min03 > min03_mdrun_log.log 2>&1 ) || { echo "Failed to run command  at line ${LINENO}" && exit; } }
[ ! -f FXR_12-FXR_74/protein/lambda4/nve/nve.tpr ] && { gmx grompp -c FXR_12-FXR_74/protein/lambda4/min03/min03.gro -r FXR_12-FXR_74/protein/lambda4/min03/min03.gro -f FXR_12-FXR_74/protein/lambda4/nve/nve.mdp -p FXR_12-FXR_74/protein/lambda4/nve/../SystemFull.top -o FXR_12-FXR_74/protein/lambda4/nve/nve.tpr -n FXR_12-FXR_74/protein/lambda4/nve/../index.ndx -po FXR_12-FXR_74/protein/lambda4/nve/nve_mdout.mdp -maxwarn 3 > FXR_12-FXR_74/protein/lambda4/nve/nve_grompp.log 2>&1 || { echo "Failed to run command  at line ${LINENO}" && exit; } }
[ ! -f FXR_12-FXR_74/protein/lambda4/nve/nve.gro ] && { ( cd FXR_12-FXR_74/protein/lambda4/nve && gmx mdrun --deffnm nve > nve_mdrun_log.log 2>&1 ) || { echo "Failed to run command  at line ${LINENO}" && exit; } }
[ ! -f FXR_12-FXR_74/protein/lambda4/nvt/nvt.tpr ] && { gmx grompp -c FXR_12-FXR_74/protein/lambda4/nve/nve.gro -r FXR_12-FXR_74/protein/lambda4/nve/nve.gro -f FXR_12-FXR_74/protein/lambda4/nvt/nvt.mdp -p FXR_12-FXR_74/protein/lambda4/nvt/../SystemFull.top -o FXR_12-FXR_74/protein/lambda4/nvt/nvt.tpr -n FXR_12-FXR_74/protein/lambda4/nvt/../index.ndx -po FXR_12-FXR_74/protein/lambda4/nvt/nvt_mdout.mdp -maxwarn 3 > FXR_12-FXR_74/protein/lambda4/nvt/nvt_grompp.log 2>&1 || { echo "Failed to run command  at line ${LINENO}" && exit; } }
[ ! -f FXR_12-FXR_74/protein/lambda4/nvt/nvt.gro ] && { ( cd FXR_12-FXR_74/protein/lambda4/nvt && gmx mdrun --deffnm nvt > nvt_mdrun_log.log 2>&1 ) || { echo "Failed to run command  at line ${LINENO}" && exit; } }
[ ! -f FXR_12-FXR_74/protein/lambda4/npt/npt.tpr ] && { gmx grompp -c FXR_12-FXR_74/protein/lambda4/nvt/nvt.gro -r FXR_12-FXR_74/protein/lambda4/nvt/nvt.gro -f FXR_12-FXR_74/protein/lambda4/npt/npt.mdp -p FXR_12-FXR_74/protein/lambda4/npt/../SystemFull.top -o FXR_12-FXR_74/protein/lambda4/npt/npt.tpr -n FXR_12-FXR_74/protein/lambda4/npt/../index.ndx -po FXR_12-FXR_74/protein/lambda4/npt/npt_mdout.mdp -maxwarn 3 > FXR_12-FXR_74/protein/lambda4/npt/npt_grompp.log 2>&1 || { echo "Failed to run command  at line ${LINENO}" && exit; } }
[ ! -f FXR_12-FXR_74/protein/lambda4/npt/npt.gro ] && { ( cd FXR_12-FXR_74/protein/lambda4/npt && gmx mdrun --deffnm npt > npt_mdrun_log.log 2>&1 ) || { echo "Failed to run command  at line ${LINENO}" && exit; } }
[ ! -f FXR_12-FXR_74/protein/lambda4/md/md_nocont.tpr ] && { gmx grompp -c FXR_12-FXR_74/protein/lambda4/npt/npt.gro -r FXR_12-FXR_74/protein/lambda4/npt/npt.gro -t FXR_12-FXR_74/protein/lambda4/npt/npt.cpt -f FXR_12-FXR_74/protein/lambda4/md/md_nocont.mdp -po FXR_12-FXR_74/protein/lambda4/md/mdout_nocont.mdp -o FXR_12-FXR_74/protein/lambda4/md/md_nocont.tpr -n FXR_12-FXR_74/protein/lambda4/md/../../index.ndx -p FXR_12-FXR_74/protein/lambda4/md/../SystemFull.top -maxwarn 3 > FXR_12-FXR_74/protein/lambda4/md/mdout_nocont.log 2>&1 || { echo "Failed to run command  at line ${LINENO}" && exit; } }
[ ! -f FXR_12-FXR_74/protein/lambda4/md/md.tpr ] && { gmx grompp -c FXR_12-FXR_74/protein/lambda4/npt/npt.gro -r FXR_12-FXR_74/protein/lambda4/npt/npt.gro -t FXR_12-FXR_74/protein/lambda4/npt/npt.cpt -f FXR_12-FXR_74/protein/lambda4/md/md.mdp -p FXR_12-FXR_74/protein/lambda4/md/../SystemFull.top -o FXR_12-FXR_74/protein/lambda4/md/md.tpr -n FXR_12-FXR_74/protein/lambda4/md/../../index.ndx -po FXR_12-FXR_74/protein/lambda4/md/mdout.mdp -maxwarn 3 > FXR_12-FXR_74/protein/lambda4/md/mdout.log 2>&1 || { echo "Failed to run command  at line ${LINENO}" && exit; } }
cp FXR_12-FXR_74/protein/lambda4/md/md.tpr FXR_12-FXR_74/protein/md/lambda4/lambda.tpr
cp FXR_12-FXR_74/protein/lambda4/md/md_nocont.tpr FXR_12-FXR_74/protein/md/lambda4/lambda_nocont.tpr

[ ! -f FXR_12-FXR_74/protein/lambda5/min01/min01.tpr ] && { gmx grompp -c FXR_12-FXR_74/protein/lambda5/min01/../FullSystem.pdb -r FXR_12-FXR_74/protein/lambda5/min01/../FullSystem.pdb -f FXR_12-FXR_74/protein/lambda5/min01/min01.mdp -p FXR_12-FXR_74/protein/lambda5/min01/../SystemFull.top -o FXR_12-FXR_74/protein/lambda5/min01/min01.tpr -n FXR_12-FXR_74/protein/lambda5/min01/../index.ndx -po FXR_12-FXR_74/protein/lambda5/min01/min01_mdout.mdp -maxwarn 3 > FXR_12-FXR_74/protein/lambda5/min01/min01_grompp.log 2>&1 || { echo "Failed to run command  at line ${LINENO}" && exit; } }
[ ! -f FXR_12-FXR_74/protein/lambda5/min01/min01.gro ] && { ( cd FXR_12-FXR_74/protein/lambda5/min01 && gmx mdrun --deffnm min01 > min01_mdrun_log.log 2>&1 ) || { echo "Failed to run command  at line ${LINENO}" && exit; } }
[ ! -f FXR_12-FXR_74/protein/lambda5/min02/min02.tpr ] && { gmx grompp -c FXR_12-FXR_74/protein/lambda5/min01/min01.gro -r FXR_12-FXR_74/protein/lambda5/min01/min01.gro -f FXR_12-FXR_74/protein/lambda5/min02/min02.mdp -p FXR_12-FXR_74/protein/lambda5/min02/../SystemFull.top -o FXR_12-FXR_74/protein/lambda5/min02/min02.tpr -n FXR_12-FXR_74/protein/lambda5/min02/../index.ndx -po FXR_12-FXR_74/protein/lambda5/min02/min02_mdout.mdp -maxwarn 3 > FXR_12-FXR_74/protein/lambda5/min02/min02_grompp.log 2>&1 || { echo "Failed to run command  at line ${LINENO}" && exit; } }
[ ! -f FXR_12-FXR_74/protein/lambda5/min02/min02.gro ] && { ( cd FXR_12-FXR_74/protein/lambda5/min02 && gmx mdrun --deffnm min02 > min02_mdrun_log.log 2>&1 ) || { echo "Failed to run command  at line ${LINENO}" && exit; } }
[ ! -f FXR_12-FXR_74/protein/lambda5/min03/min03.tpr ] && { gmx grompp -c FXR_12-FXR_74/protein/lambda5/min02/min02.gro -r FXR_12-FXR_74/protein/lambda5/min02/min02.gro -f FXR_12-FXR_74/protein/lambda5/min03/min03.mdp -p FXR_12-FXR_74/protein/lambda5/min03/../SystemFull.top -o FXR_12-FXR_74/protein/lambda5/min03/min03.tpr -n FXR_12-FXR_74/protein/lambda5/min03/../index.ndx -po FXR_12-FXR_74/protein/lambda5/min03/min03_mdout.mdp -maxwarn 3 > FXR_12-FXR_74/protein/lambda5/min03/min03_grompp.log 2>&1 || { echo "Failed to run command  at line ${LINENO}" && exit; } }
[ ! -f FXR_12-FXR_74/protein/lambda5/min03/min03.gro ] && { ( cd FXR_12-FXR_74/protein/lambda5/min03 && gmx mdrun --deffnm min03 > min03_mdrun_log.log 2>&1 ) || { echo "Failed to run command  at line ${LINENO}" && exit; } }
[ ! -f FXR_12-FXR_74/protein/lambda5/nve/nve.tpr ] && { gmx grompp -c FXR_12-FXR_74/protein/lambda5/min03/min03.gro -r FXR_12-FXR_74/protein/lambda5/min03/min03.gro -f FXR_12-FXR_74/protein/lambda5/nve/nve.mdp -p FXR_12-FXR_74/protein/lambda5/nve/../SystemFull.top -o FXR_12-FXR_74/protein/lambda5/nve/nve.tpr -n FXR_12-FXR_74/protein/lambda5/nve/../index.ndx -po FXR_12-FXR_74/protein/lambda5/nve/nve_mdout.mdp -maxwarn 3 > FXR_12-FXR_74/protein/lambda5/nve/nve_grompp.log 2>&1 || { echo "Failed to run command  at line ${LINENO}" && exit; } }
[ ! -f FXR_12-FXR_74/protein/lambda5/nve/nve.gro ] && { ( cd FXR_12-FXR_74/protein/lambda5/nve && gmx mdrun --deffnm nve > nve_mdrun_log.log 2>&1 ) || { echo "Failed to run command  at line ${LINENO}" && exit; } }
[ ! -f FXR_12-FXR_74/protein/lambda5/nvt/nvt.tpr ] && { gmx grompp -c FXR_12-FXR_74/protein/lambda5/nve/nve.gro -r FXR_12-FXR_74/protein/lambda5/nve/nve.gro -f FXR_12-FXR_74/protein/lambda5/nvt/nvt.mdp -p FXR_12-FXR_74/protein/lambda5/nvt/../SystemFull.top -o FXR_12-FXR_74/protein/lambda5/nvt/nvt.tpr -n FXR_12-FXR_74/protein/lambda5/nvt/../index.ndx -po FXR_12-FXR_74/protein/lambda5/nvt/nvt_mdout.mdp -maxwarn 3 > FXR_12-FXR_74/protein/lambda5/nvt/nvt_grompp.log 2>&1 || { echo "Failed to run command  at line ${LINENO}" && exit; } }
[ ! -f FXR_12-FXR_74/protein/lambda5/nvt/nvt.gro ] && { ( cd FXR_12-FXR_74/protein/lambda5/nvt && gmx mdrun --deffnm nvt > nvt_mdrun_log.log 2>&1 ) || { echo "Failed to run command  at line ${LINENO}" && exit; } }
[ ! -f FXR_12-FXR_74/protein/lambda5/npt/npt.tpr ] && { gmx grompp -c FXR_12-FXR_74/protein/lambda5/nvt/nvt.gro -r FXR_12-FXR_74/protein/lambda5/nvt/nvt.gro -f FXR_12-FXR_74/protein/lambda5/npt/npt.mdp -p FXR_12-FXR_74/protein/lambda5/npt/../SystemFull.top -o FXR_12-FXR_74/protein/lambda5/npt/npt.tpr -n FXR_12-FXR_74/protein/lambda5/npt/../index.ndx -po FXR_12-FXR_74/protein/lambda5/npt/npt_mdout.mdp -maxwarn 3 > FXR_12-FXR_74/protein/lambda5/npt/npt_grompp.log 2>&1 || { echo "Failed to run command  at line ${LINENO}" && exit; } }
[ ! -f FXR_12-FXR_74/protein/lambda5/npt/npt.gro ] && { ( cd FXR_12-FXR_74/protein/lambda5/npt && gmx mdrun --deffnm npt > npt_mdrun_log.log 2>&1 ) || { echo "Failed to run command  at line ${LINENO}" && exit; } }
[ ! -f FXR_12-FXR_74/protein/lambda5/md/md_nocont.tpr ] && { gmx grompp -c FXR_12-FXR_74/protein/lambda5/npt/npt.gro -r FXR_12-FXR_74/protein/lambda5/npt/npt.gro -t FXR_12-FXR_74/protein/lambda5/npt/npt.cpt -f FXR_12-FXR_74/protein/lambda5/md/md_nocont.mdp -po FXR_12-FXR_74/protein/lambda5/md/mdout_nocont.mdp -o FXR_12-FXR_74/protein/lambda5/md/md_nocont.tpr -n FXR_12-FXR_74/protein/lambda5/md/../../index.ndx -p FXR_12-FXR_74/protein/lambda5/md/../SystemFull.top -maxwarn 3 > FXR_12-FXR_74/protein/lambda5/md/mdout_nocont.log 2>&1 || { echo "Failed to run command  at line ${LINENO}" && exit; } }
[ ! -f FXR_12-FXR_74/protein/lambda5/md/md.tpr ] && { gmx grompp -c FXR_12-FXR_74/protein/lambda5/npt/npt.gro -r FXR_12-FXR_74/protein/lambda5/npt/npt.gro -t FXR_12-FXR_74/protein/lambda5/npt/npt.cpt -f FXR_12-FXR_74/protein/lambda5/md/md.mdp -p FXR_12-FXR_74/protein/lambda5/md/../SystemFull.top -o FXR_12-FXR_74/protein/lambda5/md/md.tpr -n FXR_12-FXR_74/protein/lambda5/md/../../index.ndx -po FXR_12-FXR_74/protein/lambda5/md/mdout.mdp -maxwarn 3 > FXR_12-FXR_74/protein/lambda5/md/mdout.log 2>&1 || { echo "Failed to run command  at line ${LINENO}" && exit; } }
cp FXR_12-FXR_74/protein/lambda5/md/md.tpr FXR_12-FXR_74/protein/md/lambda5/lambda.tpr
cp FXR_12-FXR_74/protein/lambda5/md/md_nocont.tpr FXR_12-FXR_74/protein/md/lambda5/lambda_nocont.tpr

[ ! -f FXR_12-FXR_74/protein/lambda6/min01/min01.tpr ] && { gmx grompp -c FXR_12-FXR_74/protein/lambda6/min01/../FullSystem.pdb -r FXR_12-FXR_74/protein/lambda6/min01/../FullSystem.pdb -f FXR_12-FXR_74/protein/lambda6/min01/min01.mdp -p FXR_12-FXR_74/protein/lambda6/min01/../SystemFull.top -o FXR_12-FXR_74/protein/lambda6/min01/min01.tpr -n FXR_12-FXR_74/protein/lambda6/min01/../index.ndx -po FXR_12-FXR_74/protein/lambda6/min01/min01_mdout.mdp -maxwarn 3 > FXR_12-FXR_74/protein/lambda6/min01/min01_grompp.log 2>&1 || { echo "Failed to run command  at line ${LINENO}" && exit; } }
[ ! -f FXR_12-FXR_74/protein/lambda6/min01/min01.gro ] && { ( cd FXR_12-FXR_74/protein/lambda6/min01 && gmx mdrun --deffnm min01 > min01_mdrun_log.log 2>&1 ) || { echo "Failed to run command  at line ${LINENO}" && exit; } }
[ ! -f FXR_12-FXR_74/protein/lambda6/min02/min02.tpr ] && { gmx grompp -c FXR_12-FXR_74/protein/lambda6/min01/min01.gro -r FXR_12-FXR_74/protein/lambda6/min01/min01.gro -f FXR_12-FXR_74/protein/lambda6/min02/min02.mdp -p FXR_12-FXR_74/protein/lambda6/min02/../SystemFull.top -o FXR_12-FXR_74/protein/lambda6/min02/min02.tpr -n FXR_12-FXR_74/protein/lambda6/min02/../index.ndx -po FXR_12-FXR_74/protein/lambda6/min02/min02_mdout.mdp -maxwarn 3 > FXR_12-FXR_74/protein/lambda6/min02/min02_grompp.log 2>&1 || { echo "Failed to run command  at line ${LINENO}" && exit; } }
[ ! -f FXR_12-FXR_74/protein/lambda6/min02/min02.gro ] && { ( cd FXR_12-FXR_74/protein/lambda6/min02 && gmx mdrun --deffnm min02 > min02_mdrun_log.log 2>&1 ) || { echo "Failed to run command  at line ${LINENO}" && exit; } }
[ ! -f FXR_12-FXR_74/protein/lambda6/min03/min03.tpr ] && { gmx grompp -c FXR_12-FXR_74/protein/lambda6/min02/min02.gro -r FXR_12-FXR_74/protein/lambda6/min02/min02.gro -f FXR_12-FXR_74/protein/lambda6/min03/min03.mdp -p FXR_12-FXR_74/protein/lambda6/min03/../SystemFull.top -o FXR_12-FXR_74/protein/lambda6/min03/min03.tpr -n FXR_12-FXR_74/protein/lambda6/min03/../index.ndx -po FXR_12-FXR_74/protein/lambda6/min03/min03_mdout.mdp -maxwarn 3 > FXR_12-FXR_74/protein/lambda6/min03/min03_grompp.log 2>&1 || { echo "Failed to run command  at line ${LINENO}" && exit; } }
[ ! -f FXR_12-FXR_74/protein/lambda6/min03/min03.gro ] && { ( cd FXR_12-FXR_74/protein/lambda6/min03 && gmx mdrun --deffnm min03 > min03_mdrun_log.log 2>&1 ) || { echo "Failed to run command  at line ${LINENO}" && exit; } }
[ ! -f FXR_12-FXR_74/protein/lambda6/nve/nve.tpr ] && { gmx grompp -c FXR_12-FXR_74/protein/lambda6/min03/min03.gro -r FXR_12-FXR_74/protein/lambda6/min03/min03.gro -f FXR_12-FXR_74/protein/lambda6/nve/nve.mdp -p FXR_12-FXR_74/protein/lambda6/nve/../SystemFull.top -o FXR_12-FXR_74/protein/lambda6/nve/nve.tpr -n FXR_12-FXR_74/protein/lambda6/nve/../index.ndx -po FXR_12-FXR_74/protein/lambda6/nve/nve_mdout.mdp -maxwarn 3 > FXR_12-FXR_74/protein/lambda6/nve/nve_grompp.log 2>&1 || { echo "Failed to run command  at line ${LINENO}" && exit; } }
[ ! -f FXR_12-FXR_74/protein/lambda6/nve/nve.gro ] && { ( cd FXR_12-FXR_74/protein/lambda6/nve && gmx mdrun --deffnm nve > nve_mdrun_log.log 2>&1 ) || { echo "Failed to run command  at line ${LINENO}" && exit; } }
[ ! -f FXR_12-FXR_74/protein/lambda6/nvt/nvt.tpr ] && { gmx grompp -c FXR_12-FXR_74/protein/lambda6/nve/nve.gro -r FXR_12-FXR_74/protein/lambda6/nve/nve.gro -f FXR_12-FXR_74/protein/lambda6/nvt/nvt.mdp -p FXR_12-FXR_74/protein/lambda6/nvt/../SystemFull.top -o FXR_12-FXR_74/protein/lambda6/nvt/nvt.tpr -n FXR_12-FXR_74/protein/lambda6/nvt/../index.ndx -po FXR_12-FXR_74/protein/lambda6/nvt/nvt_mdout.mdp -maxwarn 3 > FXR_12-FXR_74/protein/lambda6/nvt/nvt_grompp.log 2>&1 || { echo "Failed to run command  at line ${LINENO}" && exit; } }
[ ! -f FXR_12-FXR_74/protein/lambda6/nvt/nvt.gro ] && { ( cd FXR_12-FXR_74/protein/lambda6/nvt && gmx mdrun --deffnm nvt > nvt_mdrun_log.log 2>&1 ) || { echo "Failed to run command  at line ${LINENO}" && exit; } }
[ ! -f FXR_12-FXR_74/protein/lambda6/npt/npt.tpr ] && { gmx grompp -c FXR_12-FXR_74/protein/lambda6/nvt/nvt.gro -r FXR_12-FXR_74/protein/lambda6/nvt/nvt.gro -f FXR_12-FXR_74/protein/lambda6/npt/npt.mdp -p FXR_12-FXR_74/protein/lambda6/npt/../SystemFull.top -o FXR_12-FXR_74/protein/lambda6/npt/npt.tpr -n FXR_12-FXR_74/protein/lambda6/npt/../index.ndx -po FXR_12-FXR_74/protein/lambda6/npt/npt_mdout.mdp -maxwarn 3 > FXR_12-FXR_74/protein/lambda6/npt/npt_grompp.log 2>&1 || { echo "Failed to run command  at line ${LINENO}" && exit; } }
[ ! -f FXR_12-FXR_74/protein/lambda6/npt/npt.gro ] && { ( cd FXR_12-FXR_74/protein/lambda6/npt && gmx mdrun --deffnm npt > npt_mdrun_log.log 2>&1 ) || { echo "Failed to run command  at line ${LINENO}" && exit; } }
[ ! -f FXR_12-FXR_74/protein/lambda6/md/md_nocont.tpr ] && { gmx grompp -c FXR_12-FXR_74/protein/lambda6/npt/npt.gro -r FXR_12-FXR_74/protein/lambda6/npt/npt.gro -t FXR_12-FXR_74/protein/lambda6/npt/npt.cpt -f FXR_12-FXR_74/protein/lambda6/md/md_nocont.mdp -po FXR_12-FXR_74/protein/lambda6/md/mdout_nocont.mdp -o FXR_12-FXR_74/protein/lambda6/md/md_nocont.tpr -n FXR_12-FXR_74/protein/lambda6/md/../../index.ndx -p FXR_12-FXR_74/protein/lambda6/md/../SystemFull.top -maxwarn 3 > FXR_12-FXR_74/protein/lambda6/md/mdout_nocont.log 2>&1 || { echo "Failed to run command  at line ${LINENO}" && exit; } }
[ ! -f FXR_12-FXR_74/protein/lambda6/md/md.tpr ] && { gmx grompp -c FXR_12-FXR_74/protein/lambda6/npt/npt.gro -r FXR_12-FXR_74/protein/lambda6/npt/npt.gro -t FXR_12-FXR_74/protein/lambda6/npt/npt.cpt -f FXR_12-FXR_74/protein/lambda6/md/md.mdp -p FXR_12-FXR_74/protein/lambda6/md/../SystemFull.top -o FXR_12-FXR_74/protein/lambda6/md/md.tpr -n FXR_12-FXR_74/protein/lambda6/md/../../index.ndx -po FXR_12-FXR_74/protein/lambda6/md/mdout.mdp -maxwarn 3 > FXR_12-FXR_74/protein/lambda6/md/mdout.log 2>&1 || { echo "Failed to run command  at line ${LINENO}" && exit; } }
cp FXR_12-FXR_74/protein/lambda6/md/md.tpr FXR_12-FXR_74/protein/md/lambda6/lambda.tpr
cp FXR_12-FXR_74/protein/lambda6/md/md_nocont.tpr FXR_12-FXR_74/protein/md/lambda6/lambda_nocont.tpr

[ ! -f FXR_12-FXR_74/protein/lambda7/min01/min01.tpr ] && { gmx grompp -c FXR_12-FXR_74/protein/lambda7/min01/../FullSystem.pdb -r FXR_12-FXR_74/protein/lambda7/min01/../FullSystem.pdb -f FXR_12-FXR_74/protein/lambda7/min01/min01.mdp -p FXR_12-FXR_74/protein/lambda7/min01/../SystemFull.top -o FXR_12-FXR_74/protein/lambda7/min01/min01.tpr -n FXR_12-FXR_74/protein/lambda7/min01/../index.ndx -po FXR_12-FXR_74/protein/lambda7/min01/min01_mdout.mdp -maxwarn 3 > FXR_12-FXR_74/protein/lambda7/min01/min01_grompp.log 2>&1 || { echo "Failed to run command  at line ${LINENO}" && exit; } }
[ ! -f FXR_12-FXR_74/protein/lambda7/min01/min01.gro ] && { ( cd FXR_12-FXR_74/protein/lambda7/min01 && gmx mdrun --deffnm min01 > min01_mdrun_log.log 2>&1 ) || { echo "Failed to run command  at line ${LINENO}" && exit; } }
[ ! -f FXR_12-FXR_74/protein/lambda7/min02/min02.tpr ] && { gmx grompp -c FXR_12-FXR_74/protein/lambda7/min01/min01.gro -r FXR_12-FXR_74/protein/lambda7/min01/min01.gro -f FXR_12-FXR_74/protein/lambda7/min02/min02.mdp -p FXR_12-FXR_74/protein/lambda7/min02/../SystemFull.top -o FXR_12-FXR_74/protein/lambda7/min02/min02.tpr -n FXR_12-FXR_74/protein/lambda7/min02/../index.ndx -po FXR_12-FXR_74/protein/lambda7/min02/min02_mdout.mdp -maxwarn 3 > FXR_12-FXR_74/protein/lambda7/min02/min02_grompp.log 2>&1 || { echo "Failed to run command  at line ${LINENO}" && exit; } }
[ ! -f FXR_12-FXR_74/protein/lambda7/min02/min02.gro ] && { ( cd FXR_12-FXR_74/protein/lambda7/min02 && gmx mdrun --deffnm min02 > min02_mdrun_log.log 2>&1 ) || { echo "Failed to run command  at line ${LINENO}" && exit; } }
[ ! -f FXR_12-FXR_74/protein/lambda7/min03/min03.tpr ] && { gmx grompp -c FXR_12-FXR_74/protein/lambda7/min02/min02.gro -r FXR_12-FXR_74/protein/lambda7/min02/min02.gro -f FXR_12-FXR_74/protein/lambda7/min03/min03.mdp -p FXR_12-FXR_74/protein/lambda7/min03/../SystemFull.top -o FXR_12-FXR_74/protein/lambda7/min03/min03.tpr -n FXR_12-FXR_74/protein/lambda7/min03/../index.ndx -po FXR_12-FXR_74/protein/lambda7/min03/min03_mdout.mdp -maxwarn 3 > FXR_12-FXR_74/protein/lambda7/min03/min03_grompp.log 2>&1 || { echo "Failed to run command  at line ${LINENO}" && exit; } }
[ ! -f FXR_12-FXR_74/protein/lambda7/min03/min03.gro ] && { ( cd FXR_12-FXR_74/protein/lambda7/min03 && gmx mdrun --deffnm min03 > min03_mdrun_log.log 2>&1 ) || { echo "Failed to run command  at line ${LINENO}" && exit; } }
[ ! -f FXR_12-FXR_74/protein/lambda7/nve/nve.tpr ] && { gmx grompp -c FXR_12-FXR_74/protein/lambda7/min03/min03.gro -r FXR_12-FXR_74/protein/lambda7/min03/min03.gro -f FXR_12-FXR_74/protein/lambda7/nve/nve.mdp -p FXR_12-FXR_74/protein/lambda7/nve/../SystemFull.top -o FXR_12-FXR_74/protein/lambda7/nve/nve.tpr -n FXR_12-FXR_74/protein/lambda7/nve/../index.ndx -po FXR_12-FXR_74/protein/lambda7/nve/nve_mdout.mdp -maxwarn 3 > FXR_12-FXR_74/protein/lambda7/nve/nve_grompp.log 2>&1 || { echo "Failed to run command  at line ${LINENO}" && exit; } }
[ ! -f FXR_12-FXR_74/protein/lambda7/nve/nve.gro ] && { ( cd FXR_12-FXR_74/protein/lambda7/nve && gmx mdrun --deffnm nve > nve_mdrun_log.log 2>&1 ) || { echo "Failed to run command  at line ${LINENO}" && exit; } }
[ ! -f FXR_12-FXR_74/protein/lambda7/nvt/nvt.tpr ] && { gmx grompp -c FXR_12-FXR_74/protein/lambda7/nve/nve.gro -r FXR_12-FXR_74/protein/lambda7/nve/nve.gro -f FXR_12-FXR_74/protein/lambda7/nvt/nvt.mdp -p FXR_12-FXR_74/protein/lambda7/nvt/../SystemFull.top -o FXR_12-FXR_74/protein/lambda7/nvt/nvt.tpr -n FXR_12-FXR_74/protein/lambda7/nvt/../index.ndx -po FXR_12-FXR_74/protein/lambda7/nvt/nvt_mdout.mdp -maxwarn 3 > FXR_12-FXR_74/protein/lambda7/nvt/nvt_grompp.log 2>&1 || { echo "Failed to run command  at line ${LINENO}" && exit; } }
[ ! -f FXR_12-FXR_74/protein/lambda7/nvt/nvt.gro ] && { ( cd FXR_12-FXR_74/protein/lambda7/nvt && gmx mdrun --deffnm nvt > nvt_mdrun_log.log 2>&1 ) || { echo "Failed to run command  at line ${LINENO}" && exit; } }
[ ! -f FXR_12-FXR_74/protein/lambda7/npt/npt.tpr ] && { gmx grompp -c FXR_12-FXR_74/protein/lambda7/nvt/nvt.gro -r FXR_12-FXR_74/protein/lambda7/nvt/nvt.gro -f FXR_12-FXR_74/protein/lambda7/npt/npt.mdp -p FXR_12-FXR_74/protein/lambda7/npt/../SystemFull.top -o FXR_12-FXR_74/protein/lambda7/npt/npt.tpr -n FXR_12-FXR_74/protein/lambda7/npt/../index.ndx -po FXR_12-FXR_74/protein/lambda7/npt/npt_mdout.mdp -maxwarn 3 > FXR_12-FXR_74/protein/lambda7/npt/npt_grompp.log 2>&1 || { echo "Failed to run command  at line ${LINENO}" && exit; } }
[ ! -f FXR_12-FXR_74/protein/lambda7/npt/npt.gro ] && { ( cd FXR_12-FXR_74/protein/lambda7/npt && gmx mdrun --deffnm npt > npt_mdrun_log.log 2>&1 ) || { echo "Failed to run command  at line ${LINENO}" && exit; } }
[ ! -f FXR_12-FXR_74/protein/lambda7/md/md_nocont.tpr ] && { gmx grompp -c FXR_12-FXR_74/protein/lambda7/npt/npt.gro -r FXR_12-FXR_74/protein/lambda7/npt/npt.gro -t FXR_12-FXR_74/protein/lambda7/npt/npt.cpt -f FXR_12-FXR_74/protein/lambda7/md/md_nocont.mdp -po FXR_12-FXR_74/protein/lambda7/md/mdout_nocont.mdp -o FXR_12-FXR_74/protein/lambda7/md/md_nocont.tpr -n FXR_12-FXR_74/protein/lambda7/md/../../index.ndx -p FXR_12-FXR_74/protein/lambda7/md/../SystemFull.top -maxwarn 3 > FXR_12-FXR_74/protein/lambda7/md/mdout_nocont.log 2>&1 || { echo "Failed to run command  at line ${LINENO}" && exit; } }
[ ! -f FXR_12-FXR_74/protein/lambda7/md/md.tpr ] && { gmx grompp -c FXR_12-FXR_74/protein/lambda7/npt/npt.gro -r FXR_12-FXR_74/protein/lambda7/npt/npt.gro -t FXR_12-FXR_74/protein/lambda7/npt/npt.cpt -f FXR_12-FXR_74/protein/lambda7/md/md.mdp -p FXR_12-FXR_74/protein/lambda7/md/../SystemFull.top -o FXR_12-FXR_74/protein/lambda7/md/md.tpr -n FXR_12-FXR_74/protein/lambda7/md/../../index.ndx -po FXR_12-FXR_74/protein/lambda7/md/mdout.mdp -maxwarn 3 > FXR_12-FXR_74/protein/lambda7/md/mdout.log 2>&1 || { echo "Failed to run command  at line ${LINENO}" && exit; } }
cp FXR_12-FXR_74/protein/lambda7/md/md.tpr FXR_12-FXR_74/protein/md/lambda7/lambda.tpr
cp FXR_12-FXR_74/protein/lambda7/md/md_nocont.tpr FXR_12-FXR_74/protein/md/lambda7/lambda_nocont.tpr

[ ! -f FXR_12-FXR_74/protein/lambda8/min01/min01.tpr ] && { gmx grompp -c FXR_12-FXR_74/protein/lambda8/min01/../FullSystem.pdb -r FXR_12-FXR_74/protein/lambda8/min01/../FullSystem.pdb -f FXR_12-FXR_74/protein/lambda8/min01/min01.mdp -p FXR_12-FXR_74/protein/lambda8/min01/../SystemFull.top -o FXR_12-FXR_74/protein/lambda8/min01/min01.tpr -n FXR_12-FXR_74/protein/lambda8/min01/../index.ndx -po FXR_12-FXR_74/protein/lambda8/min01/min01_mdout.mdp -maxwarn 3 > FXR_12-FXR_74/protein/lambda8/min01/min01_grompp.log 2>&1 || { echo "Failed to run command  at line ${LINENO}" && exit; } }
[ ! -f FXR_12-FXR_74/protein/lambda8/min01/min01.gro ] && { ( cd FXR_12-FXR_74/protein/lambda8/min01 && gmx mdrun --deffnm min01 > min01_mdrun_log.log 2>&1 ) || { echo "Failed to run command  at line ${LINENO}" && exit; } }
[ ! -f FXR_12-FXR_74/protein/lambda8/min02/min02.tpr ] && { gmx grompp -c FXR_12-FXR_74/protein/lambda8/min01/min01.gro -r FXR_12-FXR_74/protein/lambda8/min01/min01.gro -f FXR_12-FXR_74/protein/lambda8/min02/min02.mdp -p FXR_12-FXR_74/protein/lambda8/min02/../SystemFull.top -o FXR_12-FXR_74/protein/lambda8/min02/min02.tpr -n FXR_12-FXR_74/protein/lambda8/min02/../index.ndx -po FXR_12-FXR_74/protein/lambda8/min02/min02_mdout.mdp -maxwarn 3 > FXR_12-FXR_74/protein/lambda8/min02/min02_grompp.log 2>&1 || { echo "Failed to run command  at line ${LINENO}" && exit; } }
[ ! -f FXR_12-FXR_74/protein/lambda8/min02/min02.gro ] && { ( cd FXR_12-FXR_74/protein/lambda8/min02 && gmx mdrun --deffnm min02 > min02_mdrun_log.log 2>&1 ) || { echo "Failed to run command  at line ${LINENO}" && exit; } }
[ ! -f FXR_12-FXR_74/protein/lambda8/min03/min03.tpr ] && { gmx grompp -c FXR_12-FXR_74/protein/lambda8/min02/min02.gro -r FXR_12-FXR_74/protein/lambda8/min02/min02.gro -f FXR_12-FXR_74/protein/lambda8/min03/min03.mdp -p FXR_12-FXR_74/protein/lambda8/min03/../SystemFull.top -o FXR_12-FXR_74/protein/lambda8/min03/min03.tpr -n FXR_12-FXR_74/protein/lambda8/min03/../index.ndx -po FXR_12-FXR_74/protein/lambda8/min03/min03_mdout.mdp -maxwarn 3 > FXR_12-FXR_74/protein/lambda8/min03/min03_grompp.log 2>&1 || { echo "Failed to run command  at line ${LINENO}" && exit; } }
[ ! -f FXR_12-FXR_74/protein/lambda8/min03/min03.gro ] && { ( cd FXR_12-FXR_74/protein/lambda8/min03 && gmx mdrun --deffnm min03 > min03_mdrun_log.log 2>&1 ) || { echo "Failed to run command  at line ${LINENO}" && exit; } }
[ ! -f FXR_12-FXR_74/protein/lambda8/nve/nve.tpr ] && { gmx grompp -c FXR_12-FXR_74/protein/lambda8/min03/min03.gro -r FXR_12-FXR_74/protein/lambda8/min03/min03.gro -f FXR_12-FXR_74/protein/lambda8/nve/nve.mdp -p FXR_12-FXR_74/protein/lambda8/nve/../SystemFull.top -o FXR_12-FXR_74/protein/lambda8/nve/nve.tpr -n FXR_12-FXR_74/protein/lambda8/nve/../index.ndx -po FXR_12-FXR_74/protein/lambda8/nve/nve_mdout.mdp -maxwarn 3 > FXR_12-FXR_74/protein/lambda8/nve/nve_grompp.log 2>&1 || { echo "Failed to run command  at line ${LINENO}" && exit; } }
[ ! -f FXR_12-FXR_74/protein/lambda8/nve/nve.gro ] && { ( cd FXR_12-FXR_74/protein/lambda8/nve && gmx mdrun --deffnm nve > nve_mdrun_log.log 2>&1 ) || { echo "Failed to run command  at line ${LINENO}" && exit; } }
[ ! -f FXR_12-FXR_74/protein/lambda8/nvt/nvt.tpr ] && { gmx grompp -c FXR_12-FXR_74/protein/lambda8/nve/nve.gro -r FXR_12-FXR_74/protein/lambda8/nve/nve.gro -f FXR_12-FXR_74/protein/lambda8/nvt/nvt.mdp -p FXR_12-FXR_74/protein/lambda8/nvt/../SystemFull.top -o FXR_12-FXR_74/protein/lambda8/nvt/nvt.tpr -n FXR_12-FXR_74/protein/lambda8/nvt/../index.ndx -po FXR_12-FXR_74/protein/lambda8/nvt/nvt_mdout.mdp -maxwarn 3 > FXR_12-FXR_74/protein/lambda8/nvt/nvt_grompp.log 2>&1 || { echo "Failed to run command  at line ${LINENO}" && exit; } }
[ ! -f FXR_12-FXR_74/protein/lambda8/nvt/nvt.gro ] && { ( cd FXR_12-FXR_74/protein/lambda8/nvt && gmx mdrun --deffnm nvt > nvt_mdrun_log.log 2>&1 ) || { echo "Failed to run command  at line ${LINENO}" && exit; } }
[ ! -f FXR_12-FXR_74/protein/lambda8/npt/npt.tpr ] && { gmx grompp -c FXR_12-FXR_74/protein/lambda8/nvt/nvt.gro -r FXR_12-FXR_74/protein/lambda8/nvt/nvt.gro -f FXR_12-FXR_74/protein/lambda8/npt/npt.mdp -p FXR_12-FXR_74/protein/lambda8/npt/../SystemFull.top -o FXR_12-FXR_74/protein/lambda8/npt/npt.tpr -n FXR_12-FXR_74/protein/lambda8/npt/../index.ndx -po FXR_12-FXR_74/protein/lambda8/npt/npt_mdout.mdp -maxwarn 3 > FXR_12-FXR_74/protein/lambda8/npt/npt_grompp.log 2>&1 || { echo "Failed to run command  at line ${LINENO}" && exit; } }
[ ! -f FXR_12-FXR_74/protein/lambda8/npt/npt.gro ] && { ( cd FXR_12-FXR_74/protein/lambda8/npt && gmx mdrun --deffnm npt > npt_mdrun_log.log 2>&1 ) || { echo "Failed to run command  at line ${LINENO}" && exit; } }
[ ! -f FXR_12-FXR_74/protein/lambda8/md/md_nocont.tpr ] && { gmx grompp -c FXR_12-FXR_74/protein/lambda8/npt/npt.gro -r FXR_12-FXR_74/protein/lambda8/npt/npt.gro -t FXR_12-FXR_74/protein/lambda8/npt/npt.cpt -f FXR_12-FXR_74/protein/lambda8/md/md_nocont.mdp -po FXR_12-FXR_74/protein/lambda8/md/mdout_nocont.mdp -o FXR_12-FXR_74/protein/lambda8/md/md_nocont.tpr -n FXR_12-FXR_74/protein/lambda8/md/../../index.ndx -p FXR_12-FXR_74/protein/lambda8/md/../SystemFull.top -maxwarn 3 > FXR_12-FXR_74/protein/lambda8/md/mdout_nocont.log 2>&1 || { echo "Failed to run command  at line ${LINENO}" && exit; } }
[ ! -f FXR_12-FXR_74/protein/lambda8/md/md.tpr ] && { gmx grompp -c FXR_12-FXR_74/protein/lambda8/npt/npt.gro -r FXR_12-FXR_74/protein/lambda8/npt/npt.gro -t FXR_12-FXR_74/protein/lambda8/npt/npt.cpt -f FXR_12-FXR_74/protein/lambda8/md/md.mdp -p FXR_12-FXR_74/protein/lambda8/md/../SystemFull.top -o FXR_12-FXR_74/protein/lambda8/md/md.tpr -n FXR_12-FXR_74/protein/lambda8/md/../../index.ndx -po FXR_12-FXR_74/protein/lambda8/md/mdout.mdp -maxwarn 3 > FXR_12-FXR_74/protein/lambda8/md/mdout.log 2>&1 || { echo "Failed to run command  at line ${LINENO}" && exit; } }
cp FXR_12-FXR_74/protein/lambda8/md/md.tpr FXR_12-FXR_74/protein/md/lambda8/lambda.tpr
cp FXR_12-FXR_74/protein/lambda8/md/md_nocont.tpr FXR_12-FXR_74/protein/md/lambda8/lambda_nocont.tpr

[ ! -f FXR_12-FXR_74/protein/lambda9/min01/min01.tpr ] && { gmx grompp -c FXR_12-FXR_74/protein/lambda9/min01/../FullSystem.pdb -r FXR_12-FXR_74/protein/lambda9/min01/../FullSystem.pdb -f FXR_12-FXR_74/protein/lambda9/min01/min01.mdp -p FXR_12-FXR_74/protein/lambda9/min01/../SystemFull.top -o FXR_12-FXR_74/protein/lambda9/min01/min01.tpr -n FXR_12-FXR_74/protein/lambda9/min01/../index.ndx -po FXR_12-FXR_74/protein/lambda9/min01/min01_mdout.mdp -maxwarn 3 > FXR_12-FXR_74/protein/lambda9/min01/min01_grompp.log 2>&1 || { echo "Failed to run command  at line ${LINENO}" && exit; } }
[ ! -f FXR_12-FXR_74/protein/lambda9/min01/min01.gro ] && { ( cd FXR_12-FXR_74/protein/lambda9/min01 && gmx mdrun --deffnm min01 > min01_mdrun_log.log 2>&1 ) || { echo "Failed to run command  at line ${LINENO}" && exit; } }
[ ! -f FXR_12-FXR_74/protein/lambda9/min02/min02.tpr ] && { gmx grompp -c FXR_12-FXR_74/protein/lambda9/min01/min01.gro -r FXR_12-FXR_74/protein/lambda9/min01/min01.gro -f FXR_12-FXR_74/protein/lambda9/min02/min02.mdp -p FXR_12-FXR_74/protein/lambda9/min02/../SystemFull.top -o FXR_12-FXR_74/protein/lambda9/min02/min02.tpr -n FXR_12-FXR_74/protein/lambda9/min02/../index.ndx -po FXR_12-FXR_74/protein/lambda9/min02/min02_mdout.mdp -maxwarn 3 > FXR_12-FXR_74/protein/lambda9/min02/min02_grompp.log 2>&1 || { echo "Failed to run command  at line ${LINENO}" && exit; } }
[ ! -f FXR_12-FXR_74/protein/lambda9/min02/min02.gro ] && { ( cd FXR_12-FXR_74/protein/lambda9/min02 && gmx mdrun --deffnm min02 > min02_mdrun_log.log 2>&1 ) || { echo "Failed to run command  at line ${LINENO}" && exit; } }
[ ! -f FXR_12-FXR_74/protein/lambda9/min03/min03.tpr ] && { gmx grompp -c FXR_12-FXR_74/protein/lambda9/min02/min02.gro -r FXR_12-FXR_74/protein/lambda9/min02/min02.gro -f FXR_12-FXR_74/protein/lambda9/min03/min03.mdp -p FXR_12-FXR_74/protein/lambda9/min03/../SystemFull.top -o FXR_12-FXR_74/protein/lambda9/min03/min03.tpr -n FXR_12-FXR_74/protein/lambda9/min03/../index.ndx -po FXR_12-FXR_74/protein/lambda9/min03/min03_mdout.mdp -maxwarn 3 > FXR_12-FXR_74/protein/lambda9/min03/min03_grompp.log 2>&1 || { echo "Failed to run command  at line ${LINENO}" && exit; } }
[ ! -f FXR_12-FXR_74/protein/lambda9/min03/min03.gro ] && { ( cd FXR_12-FXR_74/protein/lambda9/min03 && gmx mdrun --deffnm min03 > min03_mdrun_log.log 2>&1 ) || { echo "Failed to run command  at line ${LINENO}" && exit; } }
[ ! -f FXR_12-FXR_74/protein/lambda9/nve/nve.tpr ] && { gmx grompp -c FXR_12-FXR_74/protein/lambda9/min03/min03.gro -r FXR_12-FXR_74/protein/lambda9/min03/min03.gro -f FXR_12-FXR_74/protein/lambda9/nve/nve.mdp -p FXR_12-FXR_74/protein/lambda9/nve/../SystemFull.top -o FXR_12-FXR_74/protein/lambda9/nve/nve.tpr -n FXR_12-FXR_74/protein/lambda9/nve/../index.ndx -po FXR_12-FXR_74/protein/lambda9/nve/nve_mdout.mdp -maxwarn 3 > FXR_12-FXR_74/protein/lambda9/nve/nve_grompp.log 2>&1 || { echo "Failed to run command  at line ${LINENO}" && exit; } }
[ ! -f FXR_12-FXR_74/protein/lambda9/nve/nve.gro ] && { ( cd FXR_12-FXR_74/protein/lambda9/nve && gmx mdrun --deffnm nve > nve_mdrun_log.log 2>&1 ) || { echo "Failed to run command  at line ${LINENO}" && exit; } }
[ ! -f FXR_12-FXR_74/protein/lambda9/nvt/nvt.tpr ] && { gmx grompp -c FXR_12-FXR_74/protein/lambda9/nve/nve.gro -r FXR_12-FXR_74/protein/lambda9/nve/nve.gro -f FXR_12-FXR_74/protein/lambda9/nvt/nvt.mdp -p FXR_12-FXR_74/protein/lambda9/nvt/../SystemFull.top -o FXR_12-FXR_74/protein/lambda9/nvt/nvt.tpr -n FXR_12-FXR_74/protein/lambda9/nvt/../index.ndx -po FXR_12-FXR_74/protein/lambda9/nvt/nvt_mdout.mdp -maxwarn 3 > FXR_12-FXR_74/protein/lambda9/nvt/nvt_grompp.log 2>&1 || { echo "Failed to run command  at line ${LINENO}" && exit; } }
[ ! -f FXR_12-FXR_74/protein/lambda9/nvt/nvt.gro ] && { ( cd FXR_12-FXR_74/protein/lambda9/nvt && gmx mdrun --deffnm nvt > nvt_mdrun_log.log 2>&1 ) || { echo "Failed to run command  at line ${LINENO}" && exit; } }
[ ! -f FXR_12-FXR_74/protein/lambda9/npt/npt.tpr ] && { gmx grompp -c FXR_12-FXR_74/protein/lambda9/nvt/nvt.gro -r FXR_12-FXR_74/protein/lambda9/nvt/nvt.gro -f FXR_12-FXR_74/protein/lambda9/npt/npt.mdp -p FXR_12-FXR_74/protein/lambda9/npt/../SystemFull.top -o FXR_12-FXR_74/protein/lambda9/npt/npt.tpr -n FXR_12-FXR_74/protein/lambda9/npt/../index.ndx -po FXR_12-FXR_74/protein/lambda9/npt/npt_mdout.mdp -maxwarn 3 > FXR_12-FXR_74/protein/lambda9/npt/npt_grompp.log 2>&1 || { echo "Failed to run command  at line ${LINENO}" && exit; } }
[ ! -f FXR_12-FXR_74/protein/lambda9/npt/npt.gro ] && { ( cd FXR_12-FXR_74/protein/lambda9/npt && gmx mdrun --deffnm npt > npt_mdrun_log.log 2>&1 ) || { echo "Failed to run command  at line ${LINENO}" && exit; } }
[ ! -f FXR_12-FXR_74/protein/lambda9/md/md_nocont.tpr ] && { gmx grompp -c FXR_12-FXR_74/protein/lambda9/npt/npt.gro -r FXR_12-FXR_74/protein/lambda9/npt/npt.gro -t FXR_12-FXR_74/protein/lambda9/npt/npt.cpt -f FXR_12-FXR_74/protein/lambda9/md/md_nocont.mdp -po FXR_12-FXR_74/protein/lambda9/md/mdout_nocont.mdp -o FXR_12-FXR_74/protein/lambda9/md/md_nocont.tpr -n FXR_12-FXR_74/protein/lambda9/md/../../index.ndx -p FXR_12-FXR_74/protein/lambda9/md/../SystemFull.top -maxwarn 3 > FXR_12-FXR_74/protein/lambda9/md/mdout_nocont.log 2>&1 || { echo "Failed to run command  at line ${LINENO}" && exit; } }
[ ! -f FXR_12-FXR_74/protein/lambda9/md/md.tpr ] && { gmx grompp -c FXR_12-FXR_74/protein/lambda9/npt/npt.gro -r FXR_12-FXR_74/protein/lambda9/npt/npt.gro -t FXR_12-FXR_74/protein/lambda9/npt/npt.cpt -f FXR_12-FXR_74/protein/lambda9/md/md.mdp -p FXR_12-FXR_74/protein/lambda9/md/../SystemFull.top -o FXR_12-FXR_74/protein/lambda9/md/md.tpr -n FXR_12-FXR_74/protein/lambda9/md/../../index.ndx -po FXR_12-FXR_74/protein/lambda9/md/mdout.mdp -maxwarn 3 > FXR_12-FXR_74/protein/lambda9/md/mdout.log 2>&1 || { echo "Failed to run command  at line ${LINENO}" && exit; } }
cp FXR_12-FXR_74/protein/lambda9/md/md.tpr FXR_12-FXR_74/protein/md/lambda9/lambda.tpr
cp FXR_12-FXR_74/protein/lambda9/md/md_nocont.tpr FXR_12-FXR_74/protein/md/lambda9/lambda_nocont.tpr

[ ! -f FXR_12-FXR_74/protein/lambda10/min01/min01.tpr ] && { gmx grompp -c FXR_12-FXR_74/protein/lambda10/min01/../FullSystem.pdb -r FXR_12-FXR_74/protein/lambda10/min01/../FullSystem.pdb -f FXR_12-FXR_74/protein/lambda10/min01/min01.mdp -p FXR_12-FXR_74/protein/lambda10/min01/../SystemFull.top -o FXR_12-FXR_74/protein/lambda10/min01/min01.tpr -n FXR_12-FXR_74/protein/lambda10/min01/../index.ndx -po FXR_12-FXR_74/protein/lambda10/min01/min01_mdout.mdp -maxwarn 3 > FXR_12-FXR_74/protein/lambda10/min01/min01_grompp.log 2>&1 || { echo "Failed to run command  at line ${LINENO}" && exit; } }
[ ! -f FXR_12-FXR_74/protein/lambda10/min01/min01.gro ] && { ( cd FXR_12-FXR_74/protein/lambda10/min01 && gmx mdrun --deffnm min01 > min01_mdrun_log.log 2>&1 ) || { echo "Failed to run command  at line ${LINENO}" && exit; } }
[ ! -f FXR_12-FXR_74/protein/lambda10/min02/min02.tpr ] && { gmx grompp -c FXR_12-FXR_74/protein/lambda10/min01/min01.gro -r FXR_12-FXR_74/protein/lambda10/min01/min01.gro -f FXR_12-FXR_74/protein/lambda10/min02/min02.mdp -p FXR_12-FXR_74/protein/lambda10/min02/../SystemFull.top -o FXR_12-FXR_74/protein/lambda10/min02/min02.tpr -n FXR_12-FXR_74/protein/lambda10/min02/../index.ndx -po FXR_12-FXR_74/protein/lambda10/min02/min02_mdout.mdp -maxwarn 3 > FXR_12-FXR_74/protein/lambda10/min02/min02_grompp.log 2>&1 || { echo "Failed to run command  at line ${LINENO}" && exit; } }
[ ! -f FXR_12-FXR_74/protein/lambda10/min02/min02.gro ] && { ( cd FXR_12-FXR_74/protein/lambda10/min02 && gmx mdrun --deffnm min02 > min02_mdrun_log.log 2>&1 ) || { echo "Failed to run command  at line ${LINENO}" && exit; } }
[ ! -f FXR_12-FXR_74/protein/lambda10/min03/min03.tpr ] && { gmx grompp -c FXR_12-FXR_74/protein/lambda10/min02/min02.gro -r FXR_12-FXR_74/protein/lambda10/min02/min02.gro -f FXR_12-FXR_74/protein/lambda10/min03/min03.mdp -p FXR_12-FXR_74/protein/lambda10/min03/../SystemFull.top -o FXR_12-FXR_74/protein/lambda10/min03/min03.tpr -n FXR_12-FXR_74/protein/lambda10/min03/../index.ndx -po FXR_12-FXR_74/protein/lambda10/min03/min03_mdout.mdp -maxwarn 3 > FXR_12-FXR_74/protein/lambda10/min03/min03_grompp.log 2>&1 || { echo "Failed to run command  at line ${LINENO}" && exit; } }
[ ! -f FXR_12-FXR_74/protein/lambda10/min03/min03.gro ] && { ( cd FXR_12-FXR_74/protein/lambda10/min03 && gmx mdrun --deffnm min03 > min03_mdrun_log.log 2>&1 ) || { echo "Failed to run command  at line ${LINENO}" && exit; } }
[ ! -f FXR_12-FXR_74/protein/lambda10/nve/nve.tpr ] && { gmx grompp -c FXR_12-FXR_74/protein/lambda10/min03/min03.gro -r FXR_12-FXR_74/protein/lambda10/min03/min03.gro -f FXR_12-FXR_74/protein/lambda10/nve/nve.mdp -p FXR_12-FXR_74/protein/lambda10/nve/../SystemFull.top -o FXR_12-FXR_74/protein/lambda10/nve/nve.tpr -n FXR_12-FXR_74/protein/lambda10/nve/../index.ndx -po FXR_12-FXR_74/protein/lambda10/nve/nve_mdout.mdp -maxwarn 3 > FXR_12-FXR_74/protein/lambda10/nve/nve_grompp.log 2>&1 || { echo "Failed to run command  at line ${LINENO}" && exit; } }
[ ! -f FXR_12-FXR_74/protein/lambda10/nve/nve.gro ] && { ( cd FXR_12-FXR_74/protein/lambda10/nve && gmx mdrun --deffnm nve > nve_mdrun_log.log 2>&1 ) || { echo "Failed to run command  at line ${LINENO}" && exit; } }
[ ! -f FXR_12-FXR_74/protein/lambda10/nvt/nvt.tpr ] && { gmx grompp -c FXR_12-FXR_74/protein/lambda10/nve/nve.gro -r FXR_12-FXR_74/protein/lambda10/nve/nve.gro -f FXR_12-FXR_74/protein/lambda10/nvt/nvt.mdp -p FXR_12-FXR_74/protein/lambda10/nvt/../SystemFull.top -o FXR_12-FXR_74/protein/lambda10/nvt/nvt.tpr -n FXR_12-FXR_74/protein/lambda10/nvt/../index.ndx -po FXR_12-FXR_74/protein/lambda10/nvt/nvt_mdout.mdp -maxwarn 3 > FXR_12-FXR_74/protein/lambda10/nvt/nvt_grompp.log 2>&1 || { echo "Failed to run command  at line ${LINENO}" && exit; } }
[ ! -f FXR_12-FXR_74/protein/lambda10/nvt/nvt.gro ] && { ( cd FXR_12-FXR_74/protein/lambda10/nvt && gmx mdrun --deffnm nvt > nvt_mdrun_log.log 2>&1 ) || { echo "Failed to run command  at line ${LINENO}" && exit; } }
[ ! -f FXR_12-FXR_74/protein/lambda10/npt/npt.tpr ] && { gmx grompp -c FXR_12-FXR_74/protein/lambda10/nvt/nvt.gro -r FXR_12-FXR_74/protein/lambda10/nvt/nvt.gro -f FXR_12-FXR_74/protein/lambda10/npt/npt.mdp -p FXR_12-FXR_74/protein/lambda10/npt/../SystemFull.top -o FXR_12-FXR_74/protein/lambda10/npt/npt.tpr -n FXR_12-FXR_74/protein/lambda10/npt/../index.ndx -po FXR_12-FXR_74/protein/lambda10/npt/npt_mdout.mdp -maxwarn 3 > FXR_12-FXR_74/protein/lambda10/npt/npt_grompp.log 2>&1 || { echo "Failed to run command  at line ${LINENO}" && exit; } }
[ ! -f FXR_12-FXR_74/protein/lambda10/npt/npt.gro ] && { ( cd FXR_12-FXR_74/protein/lambda10/npt && gmx mdrun --deffnm npt > npt_mdrun_log.log 2>&1 ) || { echo "Failed to run command  at line ${LINENO}" && exit; } }
[ ! -f FXR_12-FXR_74/protein/lambda10/md/md_nocont.tpr ] && { gmx grompp -c FXR_12-FXR_74/protein/lambda10/npt/npt.gro -r FXR_12-FXR_74/protein/lambda10/npt/npt.gro -t FXR_12-FXR_74/protein/lambda10/npt/npt.cpt -f FXR_12-FXR_74/protein/lambda10/md/md_nocont.mdp -po FXR_12-FXR_74/protein/lambda10/md/mdout_nocont.mdp -o FXR_12-FXR_74/protein/lambda10/md/md_nocont.tpr -n FXR_12-FXR_74/protein/lambda10/md/../../index.ndx -p FXR_12-FXR_74/protein/lambda10/md/../SystemFull.top -maxwarn 3 > FXR_12-FXR_74/protein/lambda10/md/mdout_nocont.log 2>&1 || { echo "Failed to run command  at line ${LINENO}" && exit; } }
[ ! -f FXR_12-FXR_74/protein/lambda10/md/md.tpr ] && { gmx grompp -c FXR_12-FXR_74/protein/lambda10/npt/npt.gro -r FXR_12-FXR_74/protein/lambda10/npt/npt.gro -t FXR_12-FXR_74/protein/lambda10/npt/npt.cpt -f FXR_12-FXR_74/protein/lambda10/md/md.mdp -p FXR_12-FXR_74/protein/lambda10/md/../SystemFull.top -o FXR_12-FXR_74/protein/lambda10/md/md.tpr -n FXR_12-FXR_74/protein/lambda10/md/../../index.ndx -po FXR_12-FXR_74/protein/lambda10/md/mdout.mdp -maxwarn 3 > FXR_12-FXR_74/protein/lambda10/md/mdout.log 2>&1 || { echo "Failed to run command  at line ${LINENO}" && exit; } }
cp FXR_12-FXR_74/protein/lambda10/md/md.tpr FXR_12-FXR_74/protein/md/lambda10/lambda.tpr
cp FXR_12-FXR_74/protein/lambda10/md/md_nocont.tpr FXR_12-FXR_74/protein/md/lambda10/lambda_nocont.tpr

[ ! -f FXR_12-FXR_74/protein/lambda11/min01/min01.tpr ] && { gmx grompp -c FXR_12-FXR_74/protein/lambda11/min01/../FullSystem.pdb -r FXR_12-FXR_74/protein/lambda11/min01/../FullSystem.pdb -f FXR_12-FXR_74/protein/lambda11/min01/min01.mdp -p FXR_12-FXR_74/protein/lambda11/min01/../SystemFull.top -o FXR_12-FXR_74/protein/lambda11/min01/min01.tpr -n FXR_12-FXR_74/protein/lambda11/min01/../index.ndx -po FXR_12-FXR_74/protein/lambda11/min01/min01_mdout.mdp -maxwarn 3 > FXR_12-FXR_74/protein/lambda11/min01/min01_grompp.log 2>&1 || { echo "Failed to run command  at line ${LINENO}" && exit; } }
[ ! -f FXR_12-FXR_74/protein/lambda11/min01/min01.gro ] && { ( cd FXR_12-FXR_74/protein/lambda11/min01 && gmx mdrun --deffnm min01 > min01_mdrun_log.log 2>&1 ) || { echo "Failed to run command  at line ${LINENO}" && exit; } }
[ ! -f FXR_12-FXR_74/protein/lambda11/min02/min02.tpr ] && { gmx grompp -c FXR_12-FXR_74/protein/lambda11/min01/min01.gro -r FXR_12-FXR_74/protein/lambda11/min01/min01.gro -f FXR_12-FXR_74/protein/lambda11/min02/min02.mdp -p FXR_12-FXR_74/protein/lambda11/min02/../SystemFull.top -o FXR_12-FXR_74/protein/lambda11/min02/min02.tpr -n FXR_12-FXR_74/protein/lambda11/min02/../index.ndx -po FXR_12-FXR_74/protein/lambda11/min02/min02_mdout.mdp -maxwarn 3 > FXR_12-FXR_74/protein/lambda11/min02/min02_grompp.log 2>&1 || { echo "Failed to run command  at line ${LINENO}" && exit; } }
[ ! -f FXR_12-FXR_74/protein/lambda11/min02/min02.gro ] && { ( cd FXR_12-FXR_74/protein/lambda11/min02 && gmx mdrun --deffnm min02 > min02_mdrun_log.log 2>&1 ) || { echo "Failed to run command  at line ${LINENO}" && exit; } }
[ ! -f FXR_12-FXR_74/protein/lambda11/min03/min03.tpr ] && { gmx grompp -c FXR_12-FXR_74/protein/lambda11/min02/min02.gro -r FXR_12-FXR_74/protein/lambda11/min02/min02.gro -f FXR_12-FXR_74/protein/lambda11/min03/min03.mdp -p FXR_12-FXR_74/protein/lambda11/min03/../SystemFull.top -o FXR_12-FXR_74/protein/lambda11/min03/min03.tpr -n FXR_12-FXR_74/protein/lambda11/min03/../index.ndx -po FXR_12-FXR_74/protein/lambda11/min03/min03_mdout.mdp -maxwarn 3 > FXR_12-FXR_74/protein/lambda11/min03/min03_grompp.log 2>&1 || { echo "Failed to run command  at line ${LINENO}" && exit; } }
[ ! -f FXR_12-FXR_74/protein/lambda11/min03/min03.gro ] && { ( cd FXR_12-FXR_74/protein/lambda11/min03 && gmx mdrun --deffnm min03 > min03_mdrun_log.log 2>&1 ) || { echo "Failed to run command  at line ${LINENO}" && exit; } }
[ ! -f FXR_12-FXR_74/protein/lambda11/nve/nve.tpr ] && { gmx grompp -c FXR_12-FXR_74/protein/lambda11/min03/min03.gro -r FXR_12-FXR_74/protein/lambda11/min03/min03.gro -f FXR_12-FXR_74/protein/lambda11/nve/nve.mdp -p FXR_12-FXR_74/protein/lambda11/nve/../SystemFull.top -o FXR_12-FXR_74/protein/lambda11/nve/nve.tpr -n FXR_12-FXR_74/protein/lambda11/nve/../index.ndx -po FXR_12-FXR_74/protein/lambda11/nve/nve_mdout.mdp -maxwarn 3 > FXR_12-FXR_74/protein/lambda11/nve/nve_grompp.log 2>&1 || { echo "Failed to run command  at line ${LINENO}" && exit; } }
[ ! -f FXR_12-FXR_74/protein/lambda11/nve/nve.gro ] && { ( cd FXR_12-FXR_74/protein/lambda11/nve && gmx mdrun --deffnm nve > nve_mdrun_log.log 2>&1 ) || { echo "Failed to run command  at line ${LINENO}" && exit; } }
[ ! -f FXR_12-FXR_74/protein/lambda11/nvt/nvt.tpr ] && { gmx grompp -c FXR_12-FXR_74/protein/lambda11/nve/nve.gro -r FXR_12-FXR_74/protein/lambda11/nve/nve.gro -f FXR_12-FXR_74/protein/lambda11/nvt/nvt.mdp -p FXR_12-FXR_74/protein/lambda11/nvt/../SystemFull.top -o FXR_12-FXR_74/protein/lambda11/nvt/nvt.tpr -n FXR_12-FXR_74/protein/lambda11/nvt/../index.ndx -po FXR_12-FXR_74/protein/lambda11/nvt/nvt_mdout.mdp -maxwarn 3 > FXR_12-FXR_74/protein/lambda11/nvt/nvt_grompp.log 2>&1 || { echo "Failed to run command  at line ${LINENO}" && exit; } }
[ ! -f FXR_12-FXR_74/protein/lambda11/nvt/nvt.gro ] && { ( cd FXR_12-FXR_74/protein/lambda11/nvt && gmx mdrun --deffnm nvt > nvt_mdrun_log.log 2>&1 ) || { echo "Failed to run command  at line ${LINENO}" && exit; } }
[ ! -f FXR_12-FXR_74/protein/lambda11/npt/npt.tpr ] && { gmx grompp -c FXR_12-FXR_74/protein/lambda11/nvt/nvt.gro -r FXR_12-FXR_74/protein/lambda11/nvt/nvt.gro -f FXR_12-FXR_74/protein/lambda11/npt/npt.mdp -p FXR_12-FXR_74/protein/lambda11/npt/../SystemFull.top -o FXR_12-FXR_74/protein/lambda11/npt/npt.tpr -n FXR_12-FXR_74/protein/lambda11/npt/../index.ndx -po FXR_12-FXR_74/protein/lambda11/npt/npt_mdout.mdp -maxwarn 3 > FXR_12-FXR_74/protein/lambda11/npt/npt_grompp.log 2>&1 || { echo "Failed to run command  at line ${LINENO}" && exit; } }
[ ! -f FXR_12-FXR_74/protein/lambda11/npt/npt.gro ] && { ( cd FXR_12-FXR_74/protein/lambda11/npt && gmx mdrun --deffnm npt > npt_mdrun_log.log 2>&1 ) || { echo "Failed to run command  at line ${LINENO}" && exit; } }
[ ! -f FXR_12-FXR_74/protein/lambda11/md/md_nocont.tpr ] && { gmx grompp -c FXR_12-FXR_74/protein/lambda11/npt/npt.gro -r FXR_12-FXR_74/protein/lambda11/npt/npt.gro -t FXR_12-FXR_74/protein/lambda11/npt/npt.cpt -f FXR_12-FXR_74/protein/lambda11/md/md_nocont.mdp -po FXR_12-FXR_74/protein/lambda11/md/mdout_nocont.mdp -o FXR_12-FXR_74/protein/lambda11/md/md_nocont.tpr -n FXR_12-FXR_74/protein/lambda11/md/../../index.ndx -p FXR_12-FXR_74/protein/lambda11/md/../SystemFull.top -maxwarn 3 > FXR_12-FXR_74/protein/lambda11/md/mdout_nocont.log 2>&1 || { echo "Failed to run command  at line ${LINENO}" && exit; } }
[ ! -f FXR_12-FXR_74/protein/lambda11/md/md.tpr ] && { gmx grompp -c FXR_12-FXR_74/protein/lambda11/npt/npt.gro -r FXR_12-FXR_74/protein/lambda11/npt/npt.gro -t FXR_12-FXR_74/protein/lambda11/npt/npt.cpt -f FXR_12-FXR_74/protein/lambda11/md/md.mdp -p FXR_12-FXR_74/protein/lambda11/md/../SystemFull.top -o FXR_12-FXR_74/protein/lambda11/md/md.tpr -n FXR_12-FXR_74/protein/lambda11/md/../../index.ndx -po FXR_12-FXR_74/protein/lambda11/md/mdout.mdp -maxwarn 3 > FXR_12-FXR_74/protein/lambda11/md/mdout.log 2>&1 || { echo "Failed to run command  at line ${LINENO}" && exit; } }
cp FXR_12-FXR_74/protein/lambda11/md/md.tpr FXR_12-FXR_74/protein/md/lambda11/lambda.tpr
cp FXR_12-FXR_74/protein/lambda11/md/md_nocont.tpr FXR_12-FXR_74/protein/md/lambda11/lambda_nocont.tpr


echo "$(date): Starting run in FXR_12-FXR_74 protein at $(hostname)"

cd FXR_12-FXR_74/protein/md

if [ $(ls lambda*/lambda.gro 2>/dev/null | wc -l) -eq $(ls | egrep "lambda[0-9]+$" | wc -l) ]
then
echo "[INFO] Run step already done. Going on."
else
[ $(ls lambda*/lambda.gro 2>/dev/null | wc -l) -ne 0 ] && echo "[WARNING] Some of the lambda windows are complete, but not all of them. Trying to continue anyway."
mpirun -np $(ls | egrep "lambda[0-9]+$" | wc -l) gmx mdrun -v --deffnm lambda -cpi lambda.cpt -multidir $(ls -v | egrep "lambda[0-9]+$") >& feprun_$(date "+%H%M%S_%d%m%Y").log || { echo "mdrun failed at line ${LINENO} "; exit -1; }

fi


echo "$(date): Starting rerun in FXR_12-FXR_74 protein at $(hostname)"

if [ -f 'lambda0/lambda.trr' ]
then
ext='trr'
elif [ -f 'lambda0/lambda.xtc' ]
then
ext='xtc'
else
echo "[ERROR] Could not find trajectory file in lambda0, cannot continue"
exit -1
fi

fn0_cpu_gpu () {
gpu_array=( ${CUDA_VISIBLE_DEVICES//,/ } )
mult=$(echo "print(int(${SLURM_CPUS_ON_NODE}/${#gpu_array[@]}) + 1)" | python -u)
gpu_array=( $(echo "print('${gpu_array[@]} ' * ${mult})" | python -u) )
[ ! -f rerun/rerun_struct${1}_coord${2}.edr ] && gmx mdrun -gpu_id ${gpu_array[${3}]} -ntomp ${n_cpus} -rerun lambda${2}/lambda.${ext} -s lambda${1}/lambda_nocont.tpr -e rerun/rerun_struct${1}_coord${2}.edr -g rerun/rerun_struct${1}_coord${2}.log >& rerun/rerun_struct${1}_coord${2}.out
}

fn0_cpu () {
[ ! -f rerun/rerun_struct${1}_coord${2}.edr ] && gmx mdrun -ntomp ${n_cpus} -rerun lambda${2}/lambda.${ext} -s lambda${1}/lambda_nocont.tpr -e rerun/rerun_struct${1}_coord${2}.edr -g rerun/rerun_struct${1}_coord${2}.log >& rerun/rerun_struct${1}_coord${2}.out
}

fn0_vanilla () {
[ ! -f rerun/rerun_struct${1}_coord${2}.edr ] && gmx mdrun -rerun lambda${2}/lambda.${ext} -s lambda${1}/lambda_nocont.tpr -e rerun/rerun_struct${1}_coord${2}.edr -g rerun/rerun_struct${1}_coord${2}.log >& rerun/rerun_struct${1}_coord${2}.out
}

input_n_jobs=-1

if [[ "x${input_n_jobs}" == "x-1" ]]
then
if [[ "x$SLURM_CPUS_ON_NODE" != "x" ]]
then
# This is a slurm scheduler
if [[ "x$CUDA_VISIBLE_DEVICES" != "x" ]]
then
# There are GPU assigned to this job. Use a job per GPU.
gpu_array=(${CUDA_VISIBLE_DEVICES//,/ })
n_jobs=${#gpu_array[@]}
n_cpus=$(echo "print(int($SLURM_CPUS_ON_NODE / $n_jobs))" | python3 -u)
fn() { fn0_cpu_gpu "$@" ; }
else
# There are no GPU. Use 2 CPU per run
n_cpus=2
n_jobs=$(echo "print(int($SLURM_CPUS_ON_NODE / $n_cpus))" | python3 -u)
fn() { fn0_cpu "$@" ; }
fi
elif [[ "x$PBS_NODEFILE" != "x" ]]
then
# This is a PBS scheduler
tot_cpus=$(cat $PBS_NODEFILE | wc -l)
if [[ "x$PBS_GPUFILE" != "x" ]]
then
# There are GPU assigned to this job. Use a job per GPU.
CUDA_VISIBLE_DEVICES=$(cat $PBS_GPUFILE | awk -F"-gpu" '{ printf A$2;A=","}')
gpu_array=(${CUDA_VISIBLE_DEVICES//,/ })
n_jobs=${#gpu_array[@]}
n_cpus=$(echo "print(int($tot_cpus / $n_jobs))" | python3 -u)
fn() { fn0_cpu_gpu "$@" ; }
else
# There are no GPU. Use 2 CPU per run
n_cpus=2
n_jobs=$(echo "print(int($tot_cpus / $n_cpus))" | python3 -u)
fn() { fn0_cpu "$@" ; }
fi
else
# This is another scheduler or Bash, fall back to 1 job
n_jobs=1
fn() { fn0_vanilla "$@" ; }
fi
else
n_jobs=${input_n_jobs}
fn() { fn0_vanilla "$@" ; }
fi
export -f fn
export -f fn0_cpu_gpu
export -f fn0_cpu
export -f fn0_vanilla
export n_cpus
export ext
export CUDA_VISIBLE_DEVICES

parallel --version > /dev/null 2>&1 || { echo "[ERROR] GNU parallel not found in $PATH, cannot continue" && exit -1; }

n_lambda=$(ls lambda*/lambda.tpr | wc -l)
lambda_exp=$(seq 0 $(echo ${n_lambda}-1 | bc))
echo $n_jobs
parallel --env fn0_cpu_gpu --env fn0_cpu --env fn0_vanilla --env fn --env n_cpus --env CUDA_VISIBLE_DEVICES --env ext --joblog rerun_joblog_$(date "+%H%M%S_%d%m%Y").log --jobs $n_jobs "fn {1} {2} {%}" ::: ${lambda_exp} ::: ${lambda_exp}
[ $(ls rerun/rerun_struct*_coord*.edr | wc -l) -ne $(echo ${n_lambda}^2 | bc) ] && { echo "Failed to during rerun step on line $LINENO"; exit 1; }


echo "$(date): Starting collect in FXR_12-FXR_74 protein at $(hostname)"

cd rerun || { echo "Could not cd into rerun directory, cannot continue" && exit -1; }

input_n_jobs=-1

if [[ "x${input_n_jobs}" == "-1" ]]
then
collect_n_jobs=1
else
collect_n_jobs=${input_n_jobs}
fi

parallel --jobs $collect_n_jobs '[ ! -f lambda{}.xvg ] && printf "pV\n\n" | gmx energy -f ../lambda{}/lambda.edr -o lambda{}.xvg' ::: ${lambda_exp}
parallel --jobs $collect_n_jobs '[ ! -f {.}.xvg ] && printf "Potential\n\n" | gmx energy -f {} -o {.}.xvg' ::: *.edr

[ $(ls rerun_struct*_coord*.xvg lambda*.xvg | wc -l) -ne $(echo ${n_lambda}^2 + ${n_lambda} | bc) ] && "Failed during collect step on line $LINENO"

chmod +x ../../../../collect_results_from_xvg && ./../../../../collect_results_from_xvg --temperature 298.15 --gmx_bin gmx --input *.xvg


echo "$(date): Starting analysis in FXR_12-FXR_74 protein at $(hostname)"

cd ..

if ( [ $(ls lambda*/lambda_pbc.xtc 2>/dev/null | wc -l) -ne ${n_lambda} ] && [ $(ls lambda*/lambda_pbcfit.xtc 2>/dev/null | wc -l) -ne ${n_lambda} ] )
then
parallel --jobs=1 '( [ ! -f "{.}_pbcfit.xtc" ] && [ ! -f "{.}_pbc.xtc" ] ) && printf "System\n" | gmx trjconv -pbc mol -f {} -s {.}.tpr -o {.}_pbc.xtc -n ../index.ndx -skip 100 >> {//}/analysis.log 2>&1' ::: $(ls lambda*/lambda.${ext})
[ $(ls lambda*/lambda_pbc.xtc 2>/dev/null | wc -l) -ne ${n_lambda} ] && { echo "Failed to run trjconv pbc on line $LINENO"; exit 1; }
fi

if [ $(ls lambda*/lambda_pbcfit.xtc 2>/dev/null | wc -l) -ne ${n_lambda} ]
then
parallel --jobs=$n_jobs '[ ! -f {.}_pbcfit.xtc ] && printf "C-alpha\nC-alpha\nSystem\n" | gmx trjconv -fit rot+trans -center -f {//}/lambda_pbc.xtc -s {} -o {//}/lambda_pbcfit.xtc -n ../index.ndx >> {//}/analysis.log 2>&1' ::: $(ls lambda*/lambda.tpr)
[ $(ls lambda*/lambda_pbcfit.xtc | wc -l) -ne ${n_lambda} ] && { echo "Failed to run trjconv fit on line $LINENO"; exit 1; }
rm lambda*/lambda_pbc.xtc
fi

trajectory_files=$(ls lambda*/lambda.tpr)
( parallel --jobs=$n_jobs 'printf "LIG\n" | gmx rms -f {.}_pbcfit.xtc -s {} -n ../index.ndx -fit none -o analysis/{//}_ligrmsd.xvg >> {//}/analysis.log 2>&1' ::: ${trajectory_files} ) || { echo "Failed to calculate ligand RMSD on line $LINENO"; }
( parallel --jobs=$n_jobs 'printf  "Protein\n" | gmx rms -f {.}_pbcfit.xtc -s {} -n ../index.ndx -fit none -o analysis/{//}_protrmsd.xvg >> {//}/analysis.log 2>&1' ::: ${trajectory_files} ) || { echo "Failed to calculate protein RMSD on line $LINENO"; }
( parallel --jobs=$n_jobs 'printf "LIG\n" | gmx rmsf -f {.}_pbcfit.xtc -s {} -n ../index.ndx -nofit -o analysis/{//}_ligrmsf.xvg >> {//}/analysis.log 2>&1' ::: ${trajectory_files} ) || { echo "Failed to calculate Ligand RMSF on line $LINENO"; }
( parallel --jobs=$n_jobs 'printf  "Protein\n" | gmx rmsf -f {.}_pbcfit.xtc -s {} -n ../index.ndx -res -nofit -o analysis/{//}_protrmsf.xvg >> {//}/analysis.log 2>&1' ::: ${trajectory_files} ) || { echo "Failed to calculate protein RMSF on line $LINENO"; }
( parallel --jobs=$n_jobs 'gmx distance -select \"com of group \\"LIG\\" plus com of group \\"Protein\\"\" -f {/.}_pbcfit.xtc -s {} -n ../index.ndx -oall {//}_protligdist.xvg >> {//}/analysis.log 2>&1' ::: ${trajectory_files} ) || { echo "Failed to calculate distance between ligand and protein on line $LINENO"; }
( parallel --jobs=$n_jobs 'gmx sasa -f {.}_pbcfit.xtc -s {} -n ../index.ndx -surface \"Protein\" -o analysis/{//}_protein_sasa.xvg >> {//}/analysis.log 2>&1' ::: ${trajectory_files} ) || { echo "Failed to run SASA calculation on line $LINENO"; }
